// Scripted luxury real-estate conversations for the simulated call driver
// (demo mode — no Twilio / speech-to-text). The script is assembled from the
// client's REAL context (their search, deal, portfolio, best-matched listing)
// so the live transcript, co-pilot cues and post-call recap all line up with
// what's in the CRM. With an AI key, the script is generated by Claude from
// the same context (falls back to these templates on any failure).
const prisma = require('../../lib/prisma');
const ai = require('../../ai/claude');
const U = require('../serena/util');
const { FAIR_HOUSING } = require('../serena/prompt');

function short(n) { return n ? U.moneyCompact(n) : null; }
function bedsLine(l) {
  if (!l) return null;
  const baths = l.bathsTotal || (l.bathsFull ? l.bathsFull + (l.bathsHalf ? 0.5 : 0) : null);
  return [l.beds ? `${l.beds} bedrooms` : null, baths ? `${String(baths).replace(/\.0$/, '')} baths` : null].filter(Boolean).join(', ');
}
function featureOf(l) {
  if (!l) return 'the light';
  if (l.dockLengthFt) return `the ${l.dockLengthFt}-foot dock`;
  if (l.waterfront) return 'the water frontage';
  if (l.views && l.views.length) return `the ${String(l.views[0]).toLowerCase()} views`;
  if (l.amenities && l.amenities.length) return `the ${String(l.amenities[0]).toLowerCase()}`;
  return 'the layout';
}

async function gatherContext(workspaceId, clientId, userId) {
  const [user, client] = await Promise.all([
    userId ? prisma.user.findUnique({ where: { id: userId }, select: { firstName: true, lastName: true } }) : null,
    clientId ? prisma.client.findFirst({
      where: { id: clientId, workspaceId },
      include: {
        searches: { where: { status: 'active' }, orderBy: { createdAt: 'desc' }, take: 1 },
        deals: { where: { archivedAt: null, stage: { notIn: ['closed', 'lost'] } }, orderBy: { updatedAt: 'desc' }, take: 2 },
        properties: { orderBy: { createdAt: 'desc' }, take: 3 },
      },
    }) : null,
  ]);
  let listing = null;
  if (client) {
    const m = await prisma.match.findFirst({ where: { workspaceId, clientId: client.id, listingId: { not: null }, status: { not: 'dismissed' } }, include: { listing: true }, orderBy: { score: 'desc' } });
    listing = m && m.listing;
    if (!listing && client.deals[0] && client.deals[0].listingId) listing = await prisma.listing.findFirst({ where: { id: client.deals[0].listingId, workspaceId } });
    if (!listing && client.searches[0]) {
      const s = client.searches[0];
      listing = await prisma.listing.findFirst({ where: { workspaceId, droppedAt: null, status: { in: ['active', 'coming_soon'] }, ...(s.neighborhoods.length ? { neighborhood: { in: s.neighborhoods } } : {}) }, orderBy: { listPrice: 'desc' } });
    }
  }
  return { agentFirst: (user && user.firstName) || 'there', client, listing };
}

function pickScenario({ client }) {
  if (!client) return 'unknown';
  const deal = client.deals[0];
  if (deal && deal.stage === 'under_contract') return 'under_contract';
  if (deal && ['offer_submitted', 'offer_received'].includes(deal.stage)) return deal.stage === 'offer_received' ? 'seller_offer' : 'offer';
  const owns = client.properties.find((p) => p.relationship === 'owns');
  if ((deal && ['seller_lead', 'listing_appt', 'active'].includes(deal.stage)) || (owns && owns.thinkingOfSelling) || client.type === 'seller') return 'seller';
  const rents = client.properties.find((p) => p.relationship === 'rents' && p.leaseEndsAt);
  if (client.type === 'renter' || rents) return 'renter';
  if (client.searches.length || ['buyer', 'buyer_seller', 'investor'].includes(client.type) || (deal && deal.side === 'buyer')) return 'buyer';
  return 'sphere';
}

// Each builder returns { topic, lines:[{s:'agent'|'client', text}], recap:{ bullets, suggestions } }
const BUILD = {
  buyer({ agentFirst, client, listing }) {
    const first = client.firstName || 'there';
    const s = client.searches[0];
    const hood = (listing && listing.neighborhood) || (s && s.neighborhoods[0]) || 'the neighborhood';
    const addr = listing ? U.addressOf(listing) : `a new listing in ${hood}`;
    const price = listing ? short(listing.listPrice) : null;
    const feat = featureOf(listing);
    return {
      topic: `${addr} for ${first}`,
      lines: [
        { s: 'client', text: `Hi ${agentFirst}, good timing, I was just about to call you.` },
        { s: 'agent', text: `Ha, great minds. I wanted you to hear this from me first: ${addr} just hit${price ? ` at ${price}` : ''}, and it checks almost every box on your list.` },
        { s: 'client', text: `I saw the photos last night. ${listing && listing.beds ? `${bedsLine(listing)}, ` : ''}and ${feat}? It looks incredible.` },
        { s: 'agent', text: `It shows even better in person. The light in the main living space in the late afternoon is the thing photos can't capture.` },
        { s: 'client', text: `Honestly though, part of me thinks we should wait for rates to come down before we jump on anything.` },
        { s: 'agent', text: `Totally fair. The flip side is that the moment rates drop, every buyer who's been sitting out comes back at once, and you're competing again. If you buy the right house now, you can always refinance later.` },
        { s: 'client', text: `That's true. My lender did mention a buy-down option, I just never looked at it.` },
        { s: 'agent', text: `I'll have your lender run the buy-down numbers next to a straight thirty-year so you can see both side by side.` },
        { s: 'client', text: `Okay. I also want to make sure we see a few more homes before we decide anything.` },
        { s: 'agent', text: `Absolutely, let's set this one against the two best alternatives in ${hood} the same morning. That way you're comparing apples to apples.` },
        { s: 'client', text: `I like that. Are you free Saturday morning?` },
        { s: 'agent', text: `Saturday at 11 works. I'll set up private showings back to back, starting with ${addr}.` },
        { s: 'client', text: `Perfect. Can you also send me the comps for the street before then?` },
        { s: 'agent', text: `I'll send you the closed comps within half a mile by tomorrow morning.` },
        { s: 'client', text: `Amazing. Thank you, ${agentFirst}.` },
        { s: 'agent', text: `My pleasure. I'll text you the Saturday plan tonight. Talk soon.` },
      ],
      recap: {
        sentiment: 'positive',
        summary: `${first} is excited about ${addr} but wants to see alternatives and is weighing waiting for rates. You agreed on private showings Saturday at 11, starting with ${addr}.`,
        bullets: [
          `${first} loves ${addr}${price ? ` (${price})` : ''}, especially ${feat}`,
          'Rate hesitation: you reframed (buy now, refinance later) and offered a buy-down comparison',
          'Agreed: private showings Saturday at 11:00 AM, back to back',
        ],
        suggestions: [
          { kind: 'appointment', title: `Book Saturday's showings with ${first}?`, heard: 'Saturday at 11 works. I\'ll set up private showings back to back.', fields: { type: 'showing', date: 'saturday', time: '11:00', durationMin: 120, listingId: listing ? listing.id : null } },
          { kind: 'task', title: `Send ${first} the closed comps`, heard: 'I\'ll send you the closed comps within half a mile by tomorrow morning.', fields: { title: `Send ${first} closed comps near ${addr}`, date: 'tomorrow', time: '09:00' } },
          { kind: 'task', title: 'Ask the lender for a buy-down comparison', heard: 'I\'ll have your lender run the buy-down numbers next to a straight thirty-year.', fields: { title: `Get ${first}'s lender to run buy-down vs. 30-year fixed`, date: 'tomorrow' } },
          { kind: 'text', title: `Text ${first} the Saturday plan`, heard: 'I\'ll text you the Saturday plan tonight.', fields: { body: `Hi ${first}, great talking today. Saturday we start at 11:00 at ${addr}, then two comparables nearby. I'll send the comps tomorrow morning. See you then.` } },
        ],
      },
    };
  },

  offer({ agentFirst, client, listing }) {
    const first = client.firstName || 'there';
    const deal = client.deals[0];
    const addr = (deal && (deal.propertyAddress || deal.title)) || (listing && U.addressOf(listing)) || 'the house';
    const price = short(deal && (deal.price || deal.listPrice));
    return {
      topic: `Offer strategy on ${addr}`,
      lines: [
        { s: 'agent', text: `Hi ${first}, quick update on ${addr}.` },
        { s: 'client', text: `Hi! Any news? I've been refreshing my email all morning.` },
        { s: 'agent', text: `The listing agent called. They have multiple offers and they're asking everyone for highest and best by tomorrow at five.` },
        { s: 'client', text: `Ugh. Does that mean we have to go way over${price ? ` ${price}` : ''}?` },
        { s: 'agent', text: `Not necessarily. We can win on terms, not just price. An escalation clause with a firm cap, a shorter inspection window, and proof of funds up front makes you the cleanest offer on the table.` },
        { s: 'client', text: `What would you cap the escalation at?` },
        { s: 'agent', text: `Based on the last two closed sales on the street, I'd escalate in fifteen-thousand-dollar increments up to about four percent over our current number.` },
        { s: 'client', text: `Okay, that feels reasonable. What about the inspection, I don't want to waive it completely.` },
        { s: 'agent', text: `You won't. We'll keep a seven-day inspection for major systems only, roof, seawall, HVAC, so you're protected on the things that actually matter.` },
        { s: 'client', text: `Let me talk to my husband tonight and I'll confirm first thing tomorrow.` },
        { s: 'agent', text: `Perfect. I'll draft the revised offer tonight so it's ready to sign the minute you say go.` },
        { s: 'client', text: `Great. Can we talk at 9 tomorrow?` },
        { s: 'agent', text: `Nine o'clock tomorrow. I'll call you.` },
      ],
      recap: {
        sentiment: 'neutral',
        summary: `Multiple offers on ${addr}; highest and best due tomorrow at 5. You proposed winning on terms: an escalation clause (cap about 4% over), a 7-day major-systems inspection and proof of funds up front. ${first} will confirm after talking it over tonight.`,
        bullets: [
          `Multiple offers on ${addr}, highest and best due tomorrow 5:00 PM`,
          'Strategy: escalation clause capped ~4% over, 7-day major-systems inspection, proof of funds up front',
          `${first} confirms tomorrow morning; call at 9:00 AM`,
        ],
        suggestions: [
          { kind: 'task', title: 'Draft the revised offer tonight', heard: 'I\'ll draft the revised offer tonight so it\'s ready to sign.', fields: { title: `Draft revised offer for ${addr} (escalation + 7-day inspection)`, date: 'today', time: '19:00' } },
          { kind: 'appointment', title: `Call ${first} tomorrow at 9?`, heard: 'Nine o\'clock tomorrow. I\'ll call you.', fields: { type: 'call', date: 'tomorrow', time: '09:00', durationMin: 15 } },
          { kind: 'text', title: `Text ${first} the game plan`, heard: '', fields: { body: `Hi ${first}, recap of our plan for ${addr}: escalation in $15K steps with a firm cap, a 7-day inspection on major systems, proof of funds up front. I'll have it ready to sign tonight. Talk at 9.` } },
        ],
      },
    };
  },

  seller({ agentFirst, client }) {
    const first = client.firstName || 'there';
    const own = client.properties.find((p) => p.relationship === 'owns') || client.properties[0];
    const addr = own ? U.addressOf(own) || own.neighborhood || 'your home' : 'your home';
    const est = own && own.estValue ? short(own.estValue) : null;
    return {
      topic: `Listing ${addr}`,
      lines: [
        { s: 'agent', text: `Hi ${first}, it's ${agentFirst}. Do you have a few minutes to talk about ${addr}?` },
        { s: 'client', text: `I do. We've been talking about it a lot this week, actually.` },
        { s: 'agent', text: `Good. Based on what's closed nearby, I'd position it${est ? ` around ${est}` : ' right at the top of the recent comps'}, and I'd love to walk you through the full pricing plan in person.` },
        { s: 'client', text: `Zillow says it's worth quite a bit more than that, though.` },
        { s: 'agent', text: `I hear that a lot. The Zestimate doesn't know about the renovation quality or the view corridor. Buyers and appraisers only look at closed comps, so I'll bring you the three closest closed sales from the last six months.` },
        { s: 'client', text: `Okay, that's fair. The other thing is, another agent told us they'd do it for one and a half percent.` },
        { s: 'agent', text: `I appreciate you telling me. What matters is what you net. With a private preview to my buyer list, film, and staging, my listings sell faster and closer to ask, which usually more than covers the difference.` },
        { s: 'client', text: `Can you show us that on paper?` },
        { s: 'agent', text: `Yes. I'll put together a net-to-seller comparison side by side with a discount listing, with real numbers.` },
        { s: 'client', text: `Okay. When could you come by?` },
        { s: 'agent', text: `How about Tuesday at 4? I'll bring the comps and the marketing plan.` },
        { s: 'client', text: `Tuesday at 4 is perfect.` },
        { s: 'agent', text: `Wonderful. I'll send a confirmation today.` },
      ],
      recap: {
        sentiment: 'positive',
        summary: `${first} is seriously considering selling ${addr}. Pushback on price (Zillow) and commission (a 1.5% offer); you reframed on closed comps and net-to-seller. Listing presentation set for Tuesday at 4.`,
        bullets: [
          `${first} is ready to talk listing ${addr}${est ? ` (positioned ~${est})` : ''}`,
          'Objections: Zillow value and a 1.5% competing offer; you anchored on closed comps and net-to-seller',
          'Agreed: listing presentation Tuesday at 4:00 PM',
        ],
        suggestions: [
          { kind: 'appointment', title: 'Book the listing presentation?', heard: 'How about Tuesday at 4? I\'ll bring the comps and the marketing plan.', fields: { type: 'listing_presentation', date: 'tuesday', time: '16:00', durationMin: 90 } },
          { kind: 'task', title: 'Prepare the CMA + net-to-seller sheet', heard: 'I\'ll put together a net-to-seller comparison side by side with a discount listing.', fields: { title: `CMA + net-to-seller comparison for ${addr}`, date: 'monday' } },
          { kind: 'text', title: `Confirm Tuesday with ${first}`, heard: 'I\'ll send a confirmation today.', fields: { body: `Hi ${first}, confirming Tuesday at 4:00 at ${addr}. I'll bring the closed comps and a side-by-side net-to-seller comparison. Looking forward to it.` } },
        ],
      },
    };
  },

  seller_offer(ctx) {
    const out = BUILD.offer(ctx);
    return out;
  },

  under_contract({ agentFirst, client }) {
    const first = client.firstName || 'there';
    const deal = client.deals[0];
    const addr = (deal && (deal.propertyAddress || deal.title)) || 'the property';
    return {
      topic: `Inspection on ${addr}`,
      lines: [
        { s: 'agent', text: `Hi ${first}, I have the inspection report on ${addr}.` },
        { s: 'client', text: `Okay, how bad is it? Be honest.` },
        { s: 'agent', text: `Mostly cosmetic, which is good news. The two real items are the seawall cap and one of the AC handlers, which is near the end of its life.` },
        { s: 'client', text: `Should we ask them to fix those before closing?` },
        { s: 'agent', text: `I'd ask for a credit at closing instead. Seller repairs tend to be the cheapest possible fix. A credit lets you pick your own contractor.` },
        { s: 'client', text: `How much should we ask for?` },
        { s: 'agent', text: `Let me get two contractor quotes for the seawall and the AC tomorrow, then we ask for the midpoint with the quotes attached. It's very hard to argue with.` },
        { s: 'client', text: `Smart. And we're still on track for the closing date?` },
        { s: 'agent', text: `We are. The appraisal is scheduled and the lender has everything they need.` },
        { s: 'client', text: `Great. Let me know as soon as you hear back on the quotes.` },
        { s: 'agent', text: `I'll call you Thursday with the numbers and the credit request ready to send.` },
      ],
      recap: {
        sentiment: 'positive',
        summary: `Inspection on ${addr} came back mostly cosmetic; real items are the seawall cap and an aging AC handler. Plan: get two contractor quotes, ask for a closing credit at the midpoint. Closing still on track.`,
        bullets: [
          'Inspection: mostly cosmetic; seawall cap + one AC handler are the real items',
          'Strategy: closing credit (not seller repairs) backed by two contractor quotes',
          'Closing on track; call Thursday with numbers',
        ],
        suggestions: [
          { kind: 'task', title: 'Get two contractor quotes (seawall + AC)', heard: 'Let me get two contractor quotes for the seawall and the AC tomorrow.', fields: { title: `Get 2 quotes: seawall cap + AC handler at ${addr}`, date: 'tomorrow' } },
          { kind: 'appointment', title: `Call ${first} Thursday with the numbers?`, heard: 'I\'ll call you Thursday with the numbers and the credit request ready to send.', fields: { type: 'call', date: 'thursday', time: '10:00', durationMin: 15 } },
          { kind: 'note', title: 'Save the inspection takeaways to the file', heard: '', fields: { body: 'Inspection: mostly cosmetic. Real items: seawall cap, aging AC handler. Plan: closing credit at midpoint of two contractor quotes.' } },
        ],
      },
    };
  },

  renter({ agentFirst, client }) {
    const first = client.firstName || 'there';
    const rent = client.properties.find((p) => p.relationship === 'rents');
    const addr = rent ? U.addressOf(rent) || 'your place' : 'your place';
    return {
      topic: 'Buy vs. renew',
      lines: [
        { s: 'agent', text: `Hi ${first}, ${agentFirst} here. Your lease at ${addr} is coming up, so I wanted to check in before the renewal notice lands.` },
        { s: 'client', text: `Oh right, it's soon. The landlord already hinted the rent is going up again.` },
        { s: 'agent', text: `That's what I'm seeing across the building. Have you thought about buying instead of renewing this time?` },
        { s: 'client', text: `We have, but we figured we'd wait for rates to drop first.` },
        { s: 'agent', text: `I get it. Let me run the real math for you: what you'd pay owning versus another year of rent increases, including a refinance when rates come down.` },
        { s: 'client', text: `That would actually help a lot.` },
        { s: 'agent', text: `Great. I'll send it by Friday, and if it makes sense, we can tour a few options next week.` },
        { s: 'client', text: `Sounds good. Thanks for thinking of us.` },
      ],
      recap: {
        sentiment: 'positive',
        summary: `${first}'s lease at ${addr} is ending and rent is likely going up. They're open to buying but want to wait for rates; you offered a rent-vs-own analysis by Friday.`,
        bullets: ['Lease ending soon; landlord signaling an increase', 'Open to buying; hesitant on rates', 'You owe a rent-vs-own analysis by Friday'],
        suggestions: [
          { kind: 'task', title: 'Send the rent-vs-own analysis', heard: 'I\'ll send it by Friday.', fields: { title: `Rent-vs-own analysis for ${first}`, date: 'friday' } },
          { kind: 'text', title: `Text ${first} a quick thank-you`, heard: '', fields: { body: `Hi ${first}, good catching up. I'll send the rent-vs-own numbers by Friday, including a refinance scenario. If they make sense, we can tour a few places next week.` } },
        ],
      },
    };
  },

  sphere({ agentFirst, client }) {
    const first = client.firstName || 'there';
    const own = client.properties.find((p) => p.relationship === 'owns');
    const addr = own ? U.addressOf(own) || 'the house' : 'the house';
    return {
      topic: 'Check-in',
      lines: [
        { s: 'agent', text: `Hi ${first}, it's ${agentFirst}. No agenda, I was just thinking about you and wanted to say hello.` },
        { s: 'client', text: `${agentFirst}! So good to hear from you. How's the market treating you?` },
        { s: 'agent', text: `Busy in the best way. Homes like ${addr} are getting a lot of attention right now. How are you enjoying it?` },
        { s: 'client', text: `We love it. Although we've started talking about downsizing in a year or two.` },
        { s: 'agent', text: `That's a great conversation to start early. When you're ready, I can show you what ${addr} would net today, no pressure at all.` },
        { s: 'client', text: `I'd like that, just to know the number. My neighbor is also thinking about selling, by the way.` },
        { s: 'agent', text: `I'd be glad to help them too. Feel free to pass along my number.` },
        { s: 'client', text: `I will. Let's get lunch soon.` },
        { s: 'agent', text: `Let's do it. I'll text you a couple of dates.` },
      ],
      recap: {
        sentiment: 'positive',
        summary: `Warm check-in with ${first}. They're thinking about downsizing in a year or two and want to know what ${addr} would net today. A neighbor may sell: referral opportunity. Lunch to be scheduled.`,
        bullets: [`${first} may downsize in 1–2 years; wants a valuation of ${addr}`, 'Referral: a neighbor is thinking of selling', 'You owe lunch dates'],
        suggestions: [
          { kind: 'task', title: `Prepare a quiet valuation of ${addr}`, heard: 'I can show you what it would net today.', fields: { title: `Private valuation for ${first}: ${addr}`, date: 'next week' } },
          { kind: 'text', title: `Text ${first} lunch dates`, heard: 'I\'ll text you a couple of dates.', fields: { body: `Hi ${first}, so good to catch up. Would lunch next Tuesday or Thursday work? My treat.` } },
          { kind: 'note', title: 'Log the downsizing + referral signals', heard: '', fields: { body: 'Thinking of downsizing in 1-2 years; wants a valuation. Neighbor may sell (referral).' } },
        ],
      },
    };
  },

  unknown({ agentFirst }) {
    return {
      topic: 'New caller',
      lines: [
        { s: 'agent', text: `Hi, this is ${agentFirst}.` },
        { s: 'client', text: 'Hi, I got your number from the sign on the waterfront listing. Is it still available?' },
        { s: 'agent', text: 'It is. Are you working with an agent already?' },
        { s: 'client', text: 'No, not yet. We just started looking.' },
        { s: 'agent', text: 'Wonderful. I can show it to you privately this week. Can I get your name and the best email?' },
        { s: 'client', text: 'Sure. I\'ll text you my details right after this call.' },
        { s: 'agent', text: 'Perfect. I\'ll send you the property details and a few times that work.' },
      ],
      recap: {
        sentiment: 'positive',
        summary: 'Sign call from an unrepresented buyer interested in the waterfront listing. They will text their details; you will send the property sheet and showing times.',
        bullets: ['Unrepresented buyer from the sign call', 'Interested in the waterfront listing', 'Follow up with details and showing times'],
        suggestions: [{ kind: 'task', title: 'Follow up with the sign caller', heard: 'I\'ll send you the property details and a few times that work.', fields: { title: 'Send the sign caller the property sheet + showing times', date: 'today' } }],
      },
    };
  },
};

const SCRIPT_SCHEMA = {
  type: 'object',
  properties: {
    topic: { type: 'string' },
    lines: { type: 'array', items: { type: 'object', properties: { s: { type: 'string', enum: ['agent', 'client'] }, text: { type: 'string' } } } },
  },
};

async function aiScript(ctx, scenario, base) {
  if (!ai.available() || !ctx.client) return null;
  const c = ctx.client;
  const facts = [
    `Agent first name: ${ctx.agentFirst}. Client: ${U.nameOf(c)} (${c.type}, status ${c.status}).`,
    c.searches[0] ? `Buyer search: ${[...c.searches[0].neighborhoods, ...c.searches[0].markets].join(', ')}; ${c.searches[0].bedsMin || '?'}+ beds; up to ${short(c.searches[0].priceMax) || '?'}.` : null,
    c.deals[0] ? `Open deal: ${c.deals[0].title || c.deals[0].propertyAddress} at stage ${c.deals[0].stage}${c.deals[0].price ? `, ${short(c.deals[0].price)}` : ''}.` : null,
    c.properties.length ? `Portfolio: ${c.properties.map((p) => `${p.relationship} ${U.addressOf(p) || p.neighborhood}${p.estValue ? ` est ${short(p.estValue)}` : ''}`).join('; ')}.` : null,
    ctx.listing ? `Best-matched listing: ${U.addressOf(ctx.listing)}, ${ctx.listing.neighborhood || ''}, ${short(ctx.listing.listPrice) || ''}, ${bedsLine(ctx.listing)}.` : null,
  ].filter(Boolean).join('\n');
  try {
    const out = await ai.json({
      system: `You write realistic, natural phone-call transcripts between a luxury real-estate agent and their client, used to demo a live call co-pilot. 12–16 short lines, alternating naturally. Include exactly two of these client objections, handled well by the agent: waiting for interest rates, price vs. Zillow/value, commission push-back, multiple offers / best and final, inspection repair asks, "we want to see more homes", "let me think about it". End with a concrete agreed next step (a day and time) and one or two specific things the agent promises to send or do. Use only the facts given; never invent prices or addresses beyond them. No emoji. ${FAIR_HOUSING}`,
      prompt: `Scenario: ${scenario}. Facts:\n${facts}`,
      schema: SCRIPT_SCHEMA,
      effort: 'low',
      maxTokens: 4000,
      feature: 'call_script',
      workspaceId: c.workspaceId,
    });
    if (out && Array.isArray(out.lines) && out.lines.length >= 8) return { topic: out.topic || base.topic, lines: out.lines.slice(0, 20), recap: null };
  } catch { /* fall back */ }
  return null;
}

async function buildScript({ workspaceId, clientId, userId }) {
  const ctx = await gatherContext(workspaceId, clientId, userId);
  const scenario = pickScenario(ctx);
  const base = (BUILD[scenario] || BUILD.sphere)(ctx);
  const gen = await aiScript(ctx, scenario, base);
  return { scenario, ...(gen || base), source: gen ? 'ai' : 'template', listingId: ctx.listing ? ctx.listing.id : null };
}

module.exports = { buildScript, pickScenario, gatherContext };
