// Phone calls (3 weeks, 10 with transcripts, 4 voicemails, 1 missed today)
// and client notes. Transcript lines: ['a' | 'c', text] (agent / client).
module.exports = function buildCalls() {
  const S = (id, kind, title, detail) => ({ id, kind, title, detail, status: 'pending' });
  const calls = [
    { client: 'simone', dir: 'inbound', status: 'missed', day: 0, time: '08:55', dur: 0 },
    { client: 'victor', dir: 'inbound', status: 'voicemail', day: 0, time: '07:20', dur: 41,
      voicemail: { heard: false, text: 'Alex, Victor Hartmann. I heard at the club that the lot next to the Seagrape Shore house may come up — the owner’s kids want to sell. Call me before anyone else does. Thank you.' } },
    { client: 'rachel', dir: 'outbound', status: 'completed', day: 0, time: '08:20', dur: 260, summary: 'Confirmed Bayline sent Okafor’s final wire instructions and that Rachel will take his verification call. Closing package is ready.' },
    {
      client: 'reid', dir: 'inbound', status: 'completed', day: -1, time: '19:55', dur: 724, sentiment: 'positive',
      transcript: [
        ['a', 'Reid, hi — saw your email come through. Talk me through it.'],
        ['c', 'Alex. My buyers want 128 Sunset. They’re at seventeen-two, all cash, 14-day inspection, 45 days to close.'],
        ['a', 'That’s a real offer. Who are they?'],
        ['c', 'Family relocating from Greenwich. He sold a stake in his fund this spring. Kids start school here in January, so the 45 days matters.'],
        ['a', 'My sellers are attached to that house and the traffic has been strong. Seventeen-two is going to land hard.'],
        ['c', 'I know it’s light. They’ll move — I just don’t think they get to eighteen seventy-five.'],
        ['a', 'Anything besides price that matters to them? Furniture, the lift, timing?'],
        ['c', 'They’d want the roof-deck furniture and the gym equipment. And they’d love a lease-back if your sellers need time.'],
        ['a', 'Helpful. I’ll present tonight and get you an answer tomorrow afternoon.'],
        ['c', 'Appreciate it. They really love it — the wife has already picked the kids’ rooms.'],
        ['a', 'Noted. Talk tomorrow.'],
      ],
      summary: 'Reid Castellano presented a $17.2M cash offer on 128 Sunset Drive from a Greenwich family relocating for a January school start. He expects them to move up, but not to list price.',
      bullets: ['$17.2M cash · 14-day inspection · 45-day close', 'Buyer sold a fund stake; kids start school in January', 'They value the roof-deck furniture, gym equipment and an optional lease-back'],
      suggestions: [
        S('rc1', 'appointment', 'Offer review call with Graham & Sloane', '{dow:0} 1:00 PM · 30 min — net sheet and counter strategy'),
        S('rc2', 'task', 'Prepare net sheet: $17.2M vs. an $18.3M counter', 'Include the lease-back option and the furniture list'),
        S('rc3', 'text', 'Text Graham the headline terms tonight', '“Offer in: $17.2M from Reid’s buyer. Cash, 14-day inspection, 45-day close…”'),
      ],
    },
    {
      client: 'ethan', dir: 'outbound', status: 'completed', day: -1, time: '17:20', dur: 540, sentiment: 'positive',
      transcript: [
        ['a', 'Hey Ethan, quick prep for tomorrow’s inspection — got five minutes?'],
        ['c', 'Yeah, driving to the distillery. Go.'],
        ['a', 'Hank will be there at two. He does the roof with a drone and goes up a ladder wherever he needs to. Plan on about two hours.'],
        ['c', 'Good, because my buddy says the flashing on that style of roof is where they leak.'],
        ['a', 'He’ll check it. He’ll also do a wind-mitigation form, which can take real money off your insurance.'],
        ['c', 'Love that. Mara wants to know about the pool fence.'],
        ['a', 'I’ll ask the listing agent whether the panels in the garage convey. If not, SafeHarbor can install one within a week of closing.'],
        ['c', 'Perfect. Wren’s coming tomorrow too. She wants to see her room.'],
        ['a', 'Bring her. Hank is great with kids — he’ll probably let her hold the moisture meter.'],
        ['c', 'Ha. See you at two.'],
      ],
      summary: 'Inspection prep with Ethan: Hank Morrow inspects the roof by drone and ladder and runs a wind-mitigation form. Mara wants the pool fence settled; Wren is coming along.',
      bullets: ['Inspection {dow:0} 2:00 PM with Hank Morrow (about 2 hours)', 'Ethan worried about roof flashing; wants the wind-mit form for insurance', 'Pool fence: ask whether the garage panels convey'],
      suggestions: [
        S('ec1', 'task', 'Ask Ricardo if the pool-fence panels convey', 'Mara saw panels in the garage at the second showing'),
        S('ec2', 'text', 'Text Ethan the gate code and parking note', 'Gate code 4471#; park on the left of the motor court'),
        S('ec3', 'appointment', 'SafeHarbor pool-fence quote at Banyan Ridge', 'Week after closing · 45 min on site'),
      ],
    },
    { client: 'owen', dir: 'inbound', status: 'voicemail', day: -1, time: '20:15', dur: 52,
      voicemail: { heard: false, text: 'Hey Alex, it’s Owen. Brooke in Aspen found a chalet in the West End that Hannah is obsessed with — they’re talking about writing this week. Wanted you in the loop since it’s your referral. Call me tomorrow.' } },
    { client: 'marcus', dir: 'outbound', status: 'completed', day: -1, time: '10:40', dur: 380, summary: 'Marcus expects the Isola Verde appraisal report early next week; underwriting is otherwise clean. He asked for Isabella’s contact for a pre-approval.' },
    {
      client: 'victoria', dir: 'outbound', status: 'completed', day: -2, time: '14:30', dur: 1085, sentiment: 'positive',
      transcript: [
        ['a', 'Victoria, thanks for making time. I wanted you to hear this from me before it’s anywhere else.'],
        ['c', 'Go ahead.'],
        ['a', 'There’s an oceanfront owner in Golden Beach who may sell quietly after the holidays. A hundred feet on the beach, staff quarters, twelve-foot ceilings. He doesn’t want agents through the door until January.'],
        ['c', 'Why would he sell?'],
        ['a', 'He’s moving to Monaco and would rather do one quiet deal than a public listing.'],
        ['c', 'Price?'],
        ['a', 'He hasn’t named one. My guess is the low-to-mid thirties.'],
        ['c', 'And 455?'],
        ['a', 'Reduced to twenty-nine five. The beach is great. The house is fine, not special — you said so yourself.'],
        ['c', 'I did. Can I see the quiet one before Christmas?'],
        ['a', 'I’ll ask. It helps if I can tell him proof of funds is ready.'],
        ['c', 'Margot will send it. Let’s talk over dinner — {dow:0}?'],
        ['a', 'Osteria Vela, six-thirty. I’ll book it.'],
        ['c', 'Good. Two houses on paper, no more.'],
      ],
      summary: 'Told Victoria about the owner-quiet Golden Beach oceanfront (likely low-to-mid $30Ms, after the holidays) and the reduced 455 Seagrape Shore. She wants to see the quiet one before Christmas; Margot will send proof of funds. Dinner booked.',
      bullets: ['Quiet Golden Beach oceanfront — owner moving to Monaco, no agents until January', '455 Seagrape Shore reduced to $29.5M — she likes the beach, not the house', 'Dinner {dow:0} 6:30 at Osteria Vela; proof of funds coming from Margot'],
      suggestions: [
        S('vc1', 'appointment', 'Dinner with Victoria · Osteria Vela', '{dow:0} 6:30 PM · 2 hrs · Bal Harbour'),
        S('vc2', 'task', 'Ask the Golden Beach owner for a pre-holiday private walkthrough', 'Lead with proof of funds; one buyer only'),
        S('vc3', 'text', 'Confirm dinner and ask about Margot’s POF', '“Booked: {dow:0} at 6:30, Osteria Vela…”'),
      ],
    },
    { client: 'stefan', dir: 'inbound', status: 'voicemail', day: -2, time: '11:10', dur: 38,
      voicemail: { heard: true, text: 'Alex, it’s Stefan. I replied stop to the group texts — nothing personal, I just don’t read them. Call me about refinancing 1905 when you get a chance.' } },
    { client: 'jamal', dir: 'outbound', status: 'no_answer', day: -2, time: '10:15', dur: 0 },
    {
      client: 'daniel', dir: 'outbound', status: 'completed', day: -3, time: '12:40', dur: 430, sentiment: 'neutral',
      transcript: [
        ['a', 'Daniel, it’s Alex — two minutes on the wire process before closing.'],
        ['c', 'Sure, I’m between cases.'],
        ['a', 'Bayline will email the final wire instructions {dow:0}. Before you send anything, call Rachel Ostrowski at the number on Bayline’s website — not the one in the email — and read back every digit.'],
        ['c', 'Got it. Has anyone actually had this go wrong?'],
        ['a', 'A buyer in Brickell lost four hundred thousand last year to a spoofed email. It’s the most common fraud in our business.'],
        ['c', 'Wow. Okay. Andre will triple-check.'],
        ['a', 'And if anyone ever emails that the instructions changed — it’s fraud, every time. Call me.'],
        ['c', 'Understood. What else before {dow:okClose}?'],
        ['a', 'The movers’ insurance certificate for the building, and bring your ID to closing. That’s it.'],
      ],
      summary: 'Walked Daniel through wire-fraud precautions: verify Bayline’s instructions by calling Rachel at a known number. Remaining items are the movers’ COI and ID for closing.',
      bullets: ['Verify the wire by phone with Rachel Ostrowski — never trust emailed changes', 'Movers’ insurance certificate due to the building', 'Closing {dow:okClose} 10am at Bayline Title'],
    },
    { client: 'jamal', dir: 'inbound', status: 'voicemail', day: -3, time: '17:05', dur: 33,
      voicemail: { heard: true, text: 'Hey Alex, it’s Jamal. So sorry about today — Zoe spiked a fever and we’re at urgent care. I still really want to see Old Banyan. Can we redo it next week?' } },
    { client: 'rachel', dir: 'outbound', status: 'completed', day: -3, time: '09:30', dur: 310, summary: 'Bayline is ready for both upcoming closings; Rachel will hold a 10am slot for Okafor and an 11am slot for Delacroix.' },
    {
      client: 'harold', dir: 'outbound', status: 'completed', day: -4, time: '15:30', dur: 845, sentiment: 'positive',
      transcript: [
        ['a', 'Harold, how’s June doing with the stairs this week?'],
        ['c', 'Better, but she’s sleeping in the downstairs guest room now. That tells you everything.'],
        ['a', 'It does. I want to walk you through two paths. Refinance: you’d lock around six and three-quarters and the payment still goes up about forty-two hundred a month.'],
        ['c', 'And selling?'],
        ['a', 'At seven-six to eight million, after the loan and costs, you’d walk away with about four-point-three — enough to buy Aria 1402 in cash with a cushion.'],
        ['c', 'No mortgage at all. June would like that.'],
        ['a', 'And one level, elevator to the door, ocean on one side and the bay on the other.'],
        ['c', 'You know what she said about 1402? It’s the first condo that doesn’t feel like a hotel.'],
        ['a', 'That’s a good sign. Let’s walk it together next week — I’ll bring the 02-line sales history.'],
        ['c', 'Do that. And thank you for taking care of Charles. He needs someone straight with him.'],
        ['a', 'I appreciate the trust, Harold.'],
      ],
      summary: 'Compared refinancing vs. selling: a refi near 6.75% still adds about $4,200/month; selling at $7.6–8M nets about $4.3M — enough to buy Aria 1402 in cash. June likes 1402; walkthrough next week.',
      bullets: ['Refi ≈ 6.75% → +$4,200/mo; ARM resets {date:haroldReset}', 'Sale at $7.6–8M nets ≈ $4.3M → Aria 1402 in cash', 'Walk Aria 1402 next week with the 02-line sales history'],
    },
    {
      client: 'charles', dir: 'inbound', status: 'completed', day: -5, time: '10:30', dur: 1320, sentiment: 'neutral',
      transcript: [
        ['c', 'Alex, Charles Lowell. We’ve met with the other two firms. Margaret would like to hear your plan before we decide.'],
        ['a', 'Thank you, Charles. I’d love to present at the house — 45 minutes with both of you.'],
        ['c', 'One of them said twenty-four million.'],
        ['a', 'I’d be careful with that. 8 Pelican Bight has been on since spring and has dropped twice, to nineteen-eight. Buyers at this level are well informed.'],
        ['c', 'So what is your number?'],
        ['a', 'Between twenty-one and twenty-two and a half, depending on how we tell the boathouse and frontage story. I’ll show you exactly why on {dow:0}.'],
        ['c', 'Margaret’s main concern is privacy. No open houses. No strangers wandering the garden.'],
        ['a', 'Agreed — appointment-only, proof of funds before any showing, and a private broker preview for a dozen agents I trust.'],
        ['c', 'And the boat?'],
        ['a', 'Sell her separately. A buyer who wants a 64-foot sportfish will tell us.'],
        ['c', 'Good. {dow:0} at four, then.'],
      ],
      summary: 'Charles has met the other two firms (one suggested $24M). Alex positioned $21–22.5M using 8 Pelican Bight, committed to privacy-first marketing, and set the presentation for {dow:0} at 4:00.',
      bullets: ['Competitor floated $24M; 8 Pelican Bight sits at $19.8M after two cuts', 'Privacy first: appointment-only, proof of funds, private broker preview', 'Sportfish sold separately; presentation {dow:0} 4:00 PM at the house'],
    },
    { client: 'beatriz', dir: 'outbound', status: 'completed', day: -5, time: '16:10', dur: 470, summary: 'Buyer’s appraisal came in at value; loan commitment expected within a week. Beatriz is booking movers to Madrid for the week after closing.' },
    {
      client: 'nadia', dir: 'inbound', status: 'completed', day: -6, time: '14:40', dur: 960, sentiment: 'positive',
      transcript: [
        ['c', 'Hello Alex, it’s Nadia. Lukas is on the line as well.'],
        ['a', 'Hello Nadia, hello Lukas. Thank you both.'],
        ['c', 'I’ve looked at the Palmyra photos. I like that it is finished. I don’t want to choose tiles.'],
        ['a', 'You won’t have to. The 2022 renovation was done properly — the owner is a hotelier.'],
        ['c', 'How far is the tennis center?'],
        ['a', 'Two minutes on foot. The pro runs a junior program — Timur could join.'],
        ['c', 'Lukas will need the association documents and the club membership terms.'],
        ['a', 'I’ll send both today. Membership transfers with the sale; I’ll confirm the initiation fee.'],
        ['c', 'And the villa you mentioned?'],
        ['a', 'An estate sale, likely in about sixty days. The heirs want one discreet buyer. If Palmyra isn’t right, that’s our next conversation.'],
        ['c', 'Good. Let us see Palmyra {dow:0} at eleven.'],
      ],
      summary: 'Nadia (with Lukas) likes Palmyra 5122 because it’s turnkey; wants the association docs and club terms. The Fisher Island estate-sale villa is the fallback. Tour set for {dow:0} at 11.',
      bullets: ['Turnkey is the priority — no renovation', 'Send association docs + club membership terms to Lukas', 'Private tour {dow:0} 11:00; villa estate sale in ~60 days as backup'],
    },
    { client: 'lydia', dir: 'inbound', status: 'completed', day: -7, time: '10:00', dur: 540, summary: 'Lydia approved reducing Aria 1402 from $6.95M to $6.45M; the estate wants it sold before year-end. She prefers documents by email.' },
    { client: 'isabella', dir: 'outbound', status: 'no_answer', day: -7, time: '12:30', dur: 0 },
    {
      client: 'priya', dir: 'inbound', status: 'completed', day: -8, time: '09:00', dur: 1510, sentiment: 'positive',
      transcript: [
        ['c', 'Hi Alex, it’s Priya — Dev is here too.'],
        ['a', 'Hi both! Thanks for making time. Tell me about a perfect Saturday in Miami.'],
        ['c', 'Walk to coffee, kids on bikes, tennis in the afternoon. No car until dinner.'],
        ['a', 'That’s Coconut Grove, or the northern Gables near the Biltmore. Both walkable, different feel.'],
        ['c', 'Dev here — I need an office with a door. I’m on calls with Europe at six in the morning.'],
        ['a', 'Noted: two offices, one with a door that actually closes. Schools?'],
        ['c', 'Biscayne Prep is first choice — we applied for both kids. Gables Montessori is the backup.'],
        ['a', 'Then I’d focus on the Grove side. Budget?'],
        ['c', 'Marcus pre-approved us at five-point-two, and we’ll have about two million from the San Francisco house.'],
        ['a', 'So up to about seven and a half all-in — that buys a beautiful house in either neighborhood.'],
        ['c', 'And a fenced pool. Rohan can’t swim yet.'],
        ['a', 'Fenced pool, two offices, walkable, Biscayne Prep. I’ll set up the search today, and we’ll meet in person {dow:0}.'],
      ],
      summary: 'Discovery call with Priya and Dev: walkable Grove/Gables, Biscayne Prep first, two offices (one closed-door), fenced pool. Budget up to ~$7.5M with SF proceeds; in-person consult {dow:0}.',
      bullets: ['Walkability + Biscayne Prep drive the search', 'Two offices, fenced pool (Rohan can’t swim yet)', '$5.2M pre-approval + ~$2M from the SF sale'],
    },
    {
      client: 'simone', dir: 'outbound', status: 'completed', day: -8, time: '17:15', dur: 1140, sentiment: 'negative',
      transcript: [
        ['a', 'Simone, thank you for taking my call. I want to be honest about where we are.'],
        ['c', 'Nobody has made an offer. I know.'],
        ['a', 'Thirty days, eleven showings, a lot of love and no paper. The comps moved under us — 8 Pelican Bight dropped again.'],
        ['c', 'So you want me to lower the price.'],
        ['a', 'I want us to reset at twelve-nine and reintroduce it with an open house. A new price gets a fresh look from every agent who already knows the house.'],
        ['c', 'A million dollars, Alex.'],
        ['a', 'I know. It also puts you in front of buyers searching up to thirteen million, whom we are missing today.'],
        ['c', 'And if nothing happens?'],
        ['a', 'Then we’ve learned the market’s number before the holidays — and you’re in Paris by January either way.'],
        ['c', 'Let me sleep on it. I will tell you tomorrow.'],
      ],
      summary: 'Recommended resetting 2741 Fairway Isle Drive to $12.9M with a Sunday open house after 30 days without an offer. Simone was unhappy but open; she agreed by text the next morning.',
      bullets: ['30 days · 11 showings · no offers', 'Reset to $12.9M to reach the up-to-$13M search band', 'Open house to reintroduce the listing'],
    },
    { client: 'bianca', dir: 'inbound', status: 'missed', day: -9, time: '14:50', dur: 0 },
    { client: 'bianca', dir: 'outbound', status: 'completed', day: -9, time: '15:12', dur: 365, summary: 'Bianca wants a second visit to The Mariner PH 2 and asked about the lobby renovation budget; association has funded it.' },
    { client: 'lorenzo', dir: 'outbound', status: 'completed', day: -11, time: '11:00', dur: 610, summary: 'Lorenzo is moving the Casa Palmera Phase II release to January; penthouses guided around $11.5M. Ava stays first for PH-A, Rafael second for a 3BR.' },
    { client: 'rafael', dir: 'inbound', status: 'completed', day: -13, time: '16:00', dur: 290, summary: 'Rafael and Lucía on their way to the sales gallery; asked for the finish samples and the deposit timeline in writing.' },
    { client: 'harold', dir: 'outbound', status: 'completed', day: -14, time: '17:15', dur: 1230, summary: 'Harold received the ARM reset letter. Reviewed the payment jump (~$5,800/mo at reset) and a $7.6–8M value range; he and June are open to selling and going one-level.' },
    { client: 'julien', dir: 'outbound', status: 'completed', day: -15, time: '18:00', dur: 720, sentiment: 'positive',
      transcript: [
        ['a', 'Julien, I have the seller’s response on the seawall.'],
        ['c', 'Tell me.'],
        ['a', 'Nicole says they’d prefer to fix it themselves before closing.'],
        ['c', 'I don’t want their contractor touching my seawall.'],
        ['a', 'Exactly my advice. I’d hold firm on a thirty-five thousand credit — Hank’s high estimate was forty.'],
        ['c', 'And if they refuse?'],
        ['a', 'Then we meet at thirty and you still control the work. But I don’t think they will — they want to close.'],
        ['c', 'Do it. And ask for the lift service records.'],
        ['a', 'Will do. I’ll call as soon as I hear.'],
        ['c', 'Camille wants to know if the dock is safe for the kids this summer.'],
        ['a', 'Hank says yes. It’s cosmetic today.'],
      ],
      summary: 'Julien rejected a seller-performed seawall repair; Alex will hold for a $35K credit (floor $30K) and request the lift service records.',
      bullets: ['Seller offered to repair — Julien wants control of the contractor', 'Ask: $35K credit (fallback $30K)', 'Request dock-lift service records'],
    },
    { client: 'gordon', dir: 'outbound', status: 'no_answer', day: -15, time: '10:00', dur: 0 },
    { client: 'kenji', dir: 'inbound', status: 'completed', day: -16, time: '12:20', dur: 250, summary: 'Kenji asked how to file his homestead exemption; sent the county link and the March 1 deadline.' },
    { client: 'sebastian', dir: 'outbound', status: 'completed', day: -18, time: '12:00', dur: 420, summary: 'Coordinated the Duartes’ final walkthrough and utilities transfer; Ana is choosing paint colors for the nursery.' },
    { client: 'camila', dir: 'outbound', status: 'completed', day: -20, time: '13:00', dur: 540, summary: 'Thanked Camila for referring Tessa; she’s teaching a sunrise class on the beach for her birthday and invited Alex.' },
    { client: 'marcus', dir: 'inbound', status: 'completed', day: -21, time: '16:30', dur: 300, summary: 'Marcus congratulated on the Delacroix contract and is ordering a waterfront-specialist appraiser.' },
  ];

  const N = (client, body, x = {}) => ({ client, body, ...x });
  const notes = [
    N('julien', 'Belle Rive is 82 ft plus the swim platform — needs 90 ft of dock minimum and no fixed bridges. Captain checks the approach before any offer.', { pinned: true, day: -60 }),
    N('julien', 'Julien agreed to ask for a $35K credit instead of seller repairs; wants Hank’s seawall photos for his insurer.', { source: 'call', day: -15, deal: 'delacroix' }),
    N('julien', 'Appraisal visit complete. Camille is the anxious one on timing — update her first, Julien second.', { source: 'serena', day: -2, deal: 'delacroix' }),
    N('camille', 'Camille shoots large-format seascapes; the 14-ft entry wall at Isola Verde is for the big piece. Closing gift idea: museum-grade framing at Atelier Ocre.', { day: -12 }),
    N('victoria', 'Never call before 8am (she swims at 6). Logistics go to Margot Lyle; price conversations with Victoria only.', { pinned: true, day: -18 }),
    N('victoria', 'Needs one 20-ft uninterrupted wall and 12-ft ceilings on the main level. Passes on anything overlooked by a neighbor’s terrace.', { source: 'call', day: -2, deal: 'ashcombe' }),
    N('victoria', 'Golden Beach owner wants no agents until January — Victoria is the only buyer to bring early. Marisol Vega (Sandbar Realty) has a competing $25–30M buyer.', { source: 'serena', day: -1, deal: 'ashcombe' }),
    N('graham', 'Floor is $18M. Sloane handles the house, Graham handles numbers. Biscuit goes to daycare for every showing.', { pinned: true, day: -45, deal: 'whitaker' }),
    N('graham', 'Reid’s buyer: relocating from Greenwich, sold a fund stake, cash, wants a 45-day close for a January school start. Will move up, “not to 18.75.”', { source: 'call', day: -1, deal: 'whitaker', listing: 'own_sunset' }),
    N('graham', 'Showing feedback so far: the gym reads small; the roof deck is the wow; nobody has pushed back on price.', { day: -7, listing: 'own_sunset', deal: 'whitaker' }),
    N('sloane', 'Sloane loves estate sales and has a design practice — strong referral source for design clients moving to Miami.', { day: -12 }),
    N('charles', 'Interviewing Atlantica Estates and Gilded Key. He will push on commission — anchor on the marketing plan: printed book, private broker preview, international syndication.', { pinned: true, day: -15, deal: 'lowell' }),
    N('charles', 'Prefers to list after Thanksgiving unless a buyer surfaces sooner. The 64-ft sportfish “Margaret Rose” sells separately.', { source: 'call', day: -5, deal: 'lowell' }),
    N('charles', 'Margaret: privacy above all — appointment-only, no open houses, proof of funds before showings.', { day: -19, deal: 'lowell' }),
    N('harold', 'Referred Charles Lowell. Birthday {date:+6} — a wheated bourbon. June can’t do stairs after the knee replacement.', { pinned: true, day: -20 }),
    N('harold', 'ARM 3.125% → about 7.1% at reset (+$5,800/mo). House $7.6–8M. Leaning sell + Aria 1402 in cash.', { source: 'call', day: -14, deal: 'brennan' }),
    N('harold', 'Harold asked for the Aria 02-line sales history twice — send it before the walkthrough.', { source: 'serena', day: -1, deal: 'brennan' }),
    N('priya', 'Schools first: Biscayne Prep applied for both kids; Gables Montessori is the backup. Dev needs a closed-door office for 6am Europe calls. Vegetarian; Priya is training for a triathlon.', { source: 'call', day: -8, deal: 'raman' }),
    N('priya', 'Referred by Maya Goldstein — send Maya a thank-you after the consult.', { day: -19 }),
    N('ethan', 'Wren (4) and the pool: a fence is non-negotiable for Mara. Ask whether the garage panels convey.', { day: -31, deal: 'cole' }),
    N('ethan', 'Ethan asked about the roof; Hank does drone + ladder. Wants the wind-mit form for insurance.', { source: 'call', day: -1, deal: 'cole' }),
    N('mara', 'Mara’s birthday {date:+3}. Pediatric dentist with her own practice in South Miami; Sadie is nervous about switching schools.', { day: -20 }),
    N('rafael', 'PH-B deposit schedule: 10% paid; next 10% due {date:rafaelDeposit}; 10% at groundbreaking, 10% at top-off, 60% at closing. Lucía handles the wires.', { pinned: true, day: -12, deal: 'montoya' }),
    N('rafael', 'Wants a Phase II 3BR to flip at delivery — second on the list behind Ava Sinclair.', { day: -5 }),
    N('nadia', 'Turnkey only; tennis daily; Timur (7) for the island school. Lukas Brenner handles proof of funds and lawyers.', { source: 'call', day: -6, deal: 'karimova' }),
    N('nadia', 'Gate list: Nadia, Lukas, Timur. Meet at the island-side ferry landing.', { day: -1, listing: 'mls_palmyra' }),
    N('daniel', 'Co-represented with Jordan Pierce (50/50 split). The 9-ft piano needs the freight elevator — One Harbor Point confirmed it fits.', { day: -35, deal: 'okafor' }),
    N('daniel', 'Verified the wire call-back procedure with Daniel; Andre is handling the movers’ insurance certificate.', { source: 'call', day: -3, deal: 'okafor' }),
    N('lucas', 'Traveling in Lyon and Milan through month-end — email for documents; texts are failing while he roams.', { day: -2, deal: 'moreau' }),
    N('isabella', 'Needs 20+ ft of uninterrupted wall and a dog-friendly building (Lupo, Italian greyhound). Lease at Vela ends {date:+38}.', { day: -16, deal: 'ferraro' }),
    N('simone', 'Agreed to $12.9M (from $13.9M) plus a Sunday open house. Moving to Paris in January; wants it under contract before the holidays.', { source: 'call', day: -8, deal: 'laurent' }),
    N('simone', 'Coco (French bulldog) goes to Bark & Bubble during the open house — my treat.', { pinned: true, day: -1, listing: 'own_lagorce' }),
    N('beatriz', 'Buyers asked for the outdoor dining set — Beatriz said yes. Container to Madrid the week after closing.', { day: -2, deal: 'alvarez' }),
    N('lydia', 'Lives in Charleston and prefers email for documents. The estate wants it sold; approved $6.45M.', { day: -7, deal: 'fontaine' }),
    N('bianca', 'Hates the Mariner lobby, but the association has already funded the refresh — use that in the negotiation.', { day: -29, deal: 'rossi' }),
    N('malik', 'Reel Patience (62 ft) needs 8 ft at low tide and no fixed bridges to the inlet. Kemi doesn’t want Miami Beach.', { source: 'call', day: -12 }),
    N('victor', 'Wants an oceanfront lot in Golden Beach to build on; first on the Golden Beach lots waitlist.', { day: -40 }),
    N('sterling', 'Referred Victoria Ashcombe. Birthday {date:+12} — old Barolo. Palmyra 4421 purchase anniversary {date:sterlingAnniv}.', { pinned: true, day: -41 }),
    N('kenji', 'Referred Leo Ricci. Dream: Sunset Islands in three to four years — keep sending him the good ones.', { day: -24 }),
    N('henrik', 'Referred Theo Grant and Kenji Watanabe. Birthday {date:+13} — aquavit, not wine.', { day: -100 }),
    N('sebastian', 'Housewarming Saturday at 7 — bring a bottle (he likes Rioja).', { source: 'serena', day: 0 }),
    N('jonah', 'Jupiter Island: Ruth wants birds, Jonah wants golf. Cash buyer after the Old Cutler sale.', { day: -1 }),
    N('owen', 'Referred to Brooke Halvorsen (Summit Peak, Aspen) at a 25% referral fee. Owen and Hannah want ski-in/ski-out in the West End.', { day: -35, deal: 'fitzgerald' }),
    N('chloe', 'Chloe asked what her rented townhouse would sell for — likely a buyer within 12 months.', { source: 'serena', day: -2 }),
    N('stefan', 'Opted out of texts — CALL ONLY. ARM on Vela 1905 resets {date:+98}.', { pinned: true, day: -8 }),
    N('jamal', 'No-show {dow:-3}: daughter sick. Reschedule Old Banyan Road (reduced to $4.45M).', { day: -3 }),
    N('lorenzo', 'Phase II release pushed to January. Penthouses guided ~$11.5M. Ava first for PH-A; Rafael second for a 3BR.', { source: 'call', day: -11 }),
    N('marcus', 'Best lender in town for waterfront appraisals; sends families. Lunch owed for the Delacroix referral.', { day: -75 }),
  ];
  return { calls, notes };
};
