// MLS feed listings (origin 'feed'). All agents/brokerages are fictional.
const AT = ['Nicole Strand', 'Atlantica Estates'];
const GK = ['Tamsin Hollis', 'Gilded Key Real Estate'];
const PP = ['Ricardo Salinas', 'Palmetto & Pine Realty'];
const VM = ['Lucia Ferrante', 'Vista Mar Realty Group'];
const LU = ['Marcel Dupré', 'Lumière International Realty'];
const CL = ['Daphne Kowalski', 'Coastline Luxe Properties'];
const SW = ['Brandon Achebe', 'Seaward Partners'];
const OW = ['Grant Okimoto', 'Okimoto Waterfront Group'];
const MW = ['Celia Montrose', 'Montrose & Wilde'];
const HL = ['Ivan Petrakis', 'Harborline Realty'];
const PB = ['Joelle Marchand', 'Palm Beach Coastal Realty'];
const SO = ['Wyatt Sorensen', 'Sorensen Ocean Realty'];

const CONDO_AM = ['pool', 'gym', 'spa', 'concierge'];

module.exports = function mlsListings() {
  return [
    {
      key: 'mls_isola', mls: 'A11587342', status: 'pending', agent: AT, dom: 52,
      street: '41 Isola Verde Drive', neighborhood: 'Venetian Islands', propertyType: 'single_family', style: 'Tropical Modern', family: 'Tropical Modern',
      listPrice: 15500000, beds: 6, bathsFull: 7, bathsHalf: 1, sqft: 7900, lotSqft: 15000, yearBuilt: 2019, stories: 2, garage: 3,
      waterfront: 'bayfront', frontage: 100, dock: 92, views: ['bay', 'skyline', 'sunset'],
      amenities: ['pool', 'dock', 'boat_lift', 'elevator', 'gated', 'wine_room', 'home_theater', 'gym', 'summer_kitchen', 'generator', 'smart_home', 'rooftop_terrace'],
      taxAnnual: 221000, photos: 6,
      headline: 'Venetian Islands bayfront with a 92-ft dock and no fixed bridges',
      description: 'One of the few Venetian Islands homes that can berth a true yacht: a 92-ft concrete dock with 15,000-lb lift and open water to Government Cut with no fixed bridges. Inside, 12-ft ceilings, a glass wine room for 900 bottles and a primary suite facing the downtown skyline. Built in 2019 to current flood code.',
    },
    {
      key: 'mls_harborpoint', mls: 'A11602218', status: 'pending', agent: GK, dom: 95,
      street: '1 Harbor Point Drive', unitNumber: 'PH 4501', buildingName: 'One Harbor Point', neighborhood: 'Edgewater', propertyType: 'penthouse', style: 'Contemporary', family: 'Contemporary',
      listPrice: 9250000, beds: 4, bathsFull: 5, bathsHalf: 1, sqft: 5900, yearBuilt: 2022, views: ['bay', 'ocean', 'skyline'],
      amenities: ['rooftop_terrace', 'pool', 'gym', 'spa', 'concierge', 'elevator', 'smart_home'], hoaFee: 9800, taxAnnual: 131000, photos: 5,
      headline: 'Full-floor penthouse at One Harbor Point with private rooftop pool',
      description: 'The 45th floor in its entirety: 5,900 sq ft under 12-ft ceilings, a private elevator landing and a rooftop with its own pool and summer kitchen. Views run from Fisher Island to the Venetian Causeway. The music room was built with acoustic panels.',
    },
    {
      key: 'mls_banyan', mls: 'A11596031', status: 'under_contract', agent: PP, dom: 64,
      street: '8120 Banyan Ridge Lane', neighborhood: 'Pinecrest', propertyType: 'single_family', style: 'Modern', family: 'Modern',
      listPrice: 6995000, beds: 6, bathsFull: 6, bathsHalf: 1, sqft: 7050, lotSqft: 47916, yearBuilt: 2021, stories: 2, garage: 3,
      views: ['garden', 'pool'], amenities: ['pool', 'summer_kitchen', 'generator', 'smart_home', 'gym', 'gated'], taxAnnual: 101000, photos: 5,
      headline: 'New-construction modern on 1.1 acres in East Pinecrest',
      description: 'Built in 2021 on 1.1 gated acres, with a 70-ft pool, sport court and a summer kitchen big enough for a crowd. Every bedroom is en suite; the kids’ wing has its own playroom. Impact glass, standing-seam roof and a 48kW generator.',
    },
    {
      key: 'mls_aria1102', mls: 'A11538890', status: 'under_contract', agent: VM, dom: 120,
      street: '10 Harbour Crest Way', unitNumber: '1102', buildingName: 'The Aria at Bal Harbour', neighborhood: 'Bal Harbour', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary',
      listPrice: 5450000, beds: 3, bathsFull: 3, bathsHalf: 1, sqft: 2950, yearBuilt: 2016, waterfront: 'oceanfront', views: ['ocean'],
      amenities: [...CONDO_AM, 'private_beach'], hoaFee: 6200, taxAnnual: 82000, photos: 4,
      headline: 'Turnkey Aria three-bedroom, sold furnished',
      description: 'Professionally furnished and never rented, with a deep ocean terrace and Italian kitchen. Steps to the Bal Harbour shops; the building runs like a hotel.',
    },
    {
      key: 'mls_mariner', mls: 'A11610457', status: 'active', agent: LU, dom: 38,
      street: '140 Mariner Strand', unitNumber: 'PH 2', buildingName: 'The Mariner Surfside', neighborhood: 'Surfside', propertyType: 'penthouse', style: 'Contemporary', family: 'Contemporary',
      listPrice: 7100000, beds: 4, bathsFull: 4, bathsHalf: 1, sqft: 4100, yearBuilt: 2020, waterfront: 'oceanfront', views: ['ocean', 'intracoastal'],
      amenities: ['rooftop_terrace', ...CONDO_AM, 'private_beach'], hoaFee: 7900, taxAnnual: 104000, photos: 5,
      headline: 'Surfside penthouse with a 2,000-sq-ft wraparound terrace',
      description: 'A wraparound terrace on three exposures — sunrise over the ocean, sunset over the bay. Inside, white oak and travertine, a gallery hall and a primary bath with an ocean-facing tub. The lobby is due for a refresh the association has already funded.',
    },
    {
      key: 'mls_palmyra', mls: 'A11571126', status: 'active', agent: CL, dom: 71,
      street: '12 Palmyra Court', unitNumber: '5122', buildingName: 'The Palmyra at Fisher Island', neighborhood: 'Fisher Island', propertyType: 'condo', style: 'Mediterranean Revival', family: 'Mediterranean',
      listPrice: 11750000, beds: 4, bathsFull: 5, bathsHalf: 1, sqft: 5200, yearBuilt: 2008, yearRenovated: 2022, waterfront: 'oceanfront', views: ['ocean', 'skyline'],
      amenities: [...CONDO_AM, 'private_beach', 'tennis', 'guard_gated'], hoaFee: 11400, taxAnnual: 168000, photos: 6,
      headline: 'Fisher Island oceanfront with a 1,600-sq-ft terrace',
      description: 'A 2022 down-to-the-studs renovation of a direct-ocean residence at The Palmyra, with a 1,600-sq-ft terrace and cabana access at the beach club. Two-minute walk to the tennis center and the island school. Club membership is required and transferable.',
    },
    {
      key: 'mls_gb455', mls: 'A11522907', status: 'active', agent: SW, dom: 118,
      street: '455 Seagrape Shore Drive', neighborhood: 'Golden Beach', propertyType: 'estate', style: 'Contemporary', family: 'Contemporary',
      listPrice: 29500000, drop: { from: 32500000, daysAgo: 3, earlier: [{ from: 34000000, to: 32500000, daysAgo: 61 }] },
      beds: 8, bathsFull: 9, bathsHalf: 2, sqft: 12600, lotSqft: 31000, yearBuilt: 2017, stories: 3, garage: 4,
      waterfront: 'oceanfront', frontage: 100, views: ['ocean', 'sunrise'],
      amenities: ['pool', 'private_beach', 'gated', 'staff_quarters', 'gym', 'spa', 'wine_room', 'elevator', 'generator', 'smart_home', 'home_theater', 'summer_kitchen'],
      taxAnnual: 431000, photos: 6,
      headline: 'Golden Beach oceanfront, reduced to $29.5M',
      description: 'A 2017 contemporary on 100 ft of private beach with 13-ft ceilings on the main level and a two-story gallery wall. Staff quarters over a four-car garage, a hammam-style spa and a 700-bottle wine room. Reduced $3M this week; the sellers have already bought in Palm Beach.',
    },
    {
      key: 'mls_gb233', mls: 'A11604412', status: 'active', agent: OW, dom: 47,
      street: '233 Atlantic Crest Lane', neighborhood: 'Golden Beach', propertyType: 'single_family', style: 'Modern', family: 'Modern',
      listPrice: 24900000, beds: 7, bathsFull: 8, bathsHalf: 1, sqft: 9900, lotSqft: 24000, yearBuilt: 2022, stories: 2, garage: 3,
      waterfront: 'oceanfront', frontage: 75, views: ['ocean'], amenities: ['pool', 'private_beach', 'gated', 'gym', 'elevator', 'generator', 'smart_home'],
      taxAnnual: 362000, photos: 5,
      headline: 'New oceanfront modern in Golden Beach',
      description: 'Delivered in 2022 with a glass stair, a 60-ft lap pool and 75 ft on the sand. Ten-foot ceilings keep it intimate; the second floor has four en-suite bedrooms and an ocean-view study.',
    },
    {
      key: 'mls_gb517', mls: 'A11589660', status: 'active', agent: SO, dom: 83,
      street: '517 Seagrape Shore Drive', neighborhood: 'Golden Beach', propertyType: 'estate', style: 'Mediterranean Revival', family: 'Mediterranean',
      listPrice: 27750000, beds: 8, bathsFull: 8, bathsHalf: 2, sqft: 11200, lotSqft: 29500, yearBuilt: 2004, yearRenovated: 2018, stories: 2, garage: 4,
      waterfront: 'oceanfront', frontage: 110, views: ['ocean'], amenities: ['pool', 'private_beach', 'gated', 'staff_quarters', 'wine_room', 'home_theater', 'generator', 'tennis'],
      taxAnnual: 402000, photos: 5,
      headline: 'Mediterranean oceanfront with tennis in Golden Beach',
      description: 'A 110-ft oceanfront estate with a rare full tennis court, renovated in 2018 with a new kitchen and spa baths. The motor court fronts the boulevard; the beach side is completely private.',
    },
    {
      key: 'mls_star28', mls: 'A11498251', status: 'active', agent: LU, dom: 160,
      street: '28 Star Island Crescent', neighborhood: 'Star Island', propertyType: 'estate', style: 'Contemporary', family: 'Contemporary',
      listPrice: 42000000, beds: 8, bathsFull: 9, bathsHalf: 3, sqft: 14000, lotSqft: 43560, yearBuilt: 2015, stories: 2, garage: 4,
      waterfront: 'bayfront', frontage: 200, dock: 150, views: ['bay', 'skyline', 'sunset'],
      amenities: ['pool', 'dock', 'boat_lift', 'elevator', 'gated', 'guard_gated', 'guest_house', 'wine_room', 'home_theater', 'gym', 'spa', 'summer_kitchen', 'generator', 'staff_quarters'],
      taxAnnual: 640000, photos: 6,
      headline: '200 ft on the bay at the end of Star Island',
      description: 'A full acre at the tip of the island with 200 ft of seawall and a 150-ft dock — the kind of frontage that hosts a superyacht. Two-story living room, separate guest house and a cinema. Guard-gated island with a single bridge.',
    },
    {
      key: 'mls_venetian19', mls: 'A11612784', status: 'active', agent: HL, dom: 22,
      street: '19 Isola Bella Court', neighborhood: 'Venetian Islands', propertyType: 'single_family', style: 'Mediterranean Revival', family: 'Mediterranean',
      listPrice: 11400000, beds: 5, bathsFull: 5, bathsHalf: 1, sqft: 5900, lotSqft: 10500, yearBuilt: 1936, yearRenovated: 2017, stories: 2, garage: 2,
      waterfront: 'bayfront', frontage: 70, dock: 55, views: ['bay', 'skyline'], amenities: ['pool', 'dock', 'guest_house', 'generator'],
      taxAnnual: 163000, photos: 5,
      headline: '1936 Venetian Islands Mediterranean with skyline sunsets',
      description: 'A restored 1936 Mediterranean with a 55-ft dock and a pool pavilion facing the downtown skyline. Original fireplaces and a cypress-beamed living room; the guest house was rebuilt in 2017.',
    },
    {
      key: 'mls_sunset1904', mls: 'A11583319', status: 'active', agent: MW, dom: 58,
      street: '1904 Sunset Isle Way', neighborhood: 'Sunset Islands', propertyType: 'single_family', style: 'Modern', family: 'Modern',
      listPrice: 15900000, beds: 6, bathsFull: 6, bathsHalf: 2, sqft: 7700, lotSqft: 16000, yearBuilt: 2020, stories: 2, garage: 2,
      waterfront: 'bayfront', frontage: 85, dock: 80, views: ['bay', 'sunset'],
      amenities: ['pool', 'dock', 'boat_lift', 'elevator', 'gated', 'wine_room', 'gym', 'generator', 'smart_home'], taxAnnual: 228000, photos: 5,
      headline: 'Sunset Islands modern — 128 Sunset Drive’s closest comp',
      description: 'A white stucco and teak modern with 85 ft on the bay and an 80-ft dock. Double-height living room, a glass elevator and a gym that opens to the pool deck. Faces west for long sunsets.',
    },
    {
      key: 'mls_seaview1801', mls: 'A11607735', status: 'active', agent: VM, dom: 29,
      street: '26 Harbour Crest Way', unitNumber: '1801', buildingName: 'Seaview Bal Harbour', neighborhood: 'Bal Harbour', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary',
      listPrice: 4250000, beds: 3, bathsFull: 3, bathsHalf: 1, sqft: 2600, yearBuilt: 2014, waterfront: 'oceanfront', views: ['ocean', 'intracoastal'],
      amenities: [...CONDO_AM, 'private_beach'], hoaFee: 4700, taxAnnual: 63000, photos: 4,
      headline: 'Single-level oceanfront in Bal Harbour, no stairs anywhere',
      description: 'Flow-through 3BR on the 18th floor with ocean and bay terraces and a private elevator foyer. Pet-friendly building with beach service; walk to the shops.',
    },
    {
      key: 'mls_oceanique5201', mls: 'A11561049', status: 'active', agent: SO, dom: 76,
      street: '300 Oceanique Way', unitNumber: 'PH 5201', buildingName: 'Oceanique Sunny Isles', neighborhood: 'Sunny Isles', propertyType: 'penthouse', style: 'Contemporary', family: 'Contemporary',
      listPrice: 5650000, drop: { from: 5995000, daysAgo: 2 }, beds: 4, bathsFull: 4, bathsHalf: 1, sqft: 4000, yearBuilt: 2018, waterfront: 'oceanfront', views: ['ocean', 'intracoastal'],
      amenities: [...CONDO_AM, 'private_beach', 'rooftop_terrace'], hoaFee: 6900, taxAnnual: 86000, photos: 5,
      headline: 'Sunny Isles penthouse, 52 floors up — reduced',
      description: 'Ten-foot glass on every side, a summer kitchen on the ocean terrace and a private rooftop deck. Reduced $345K on Tuesday; the seller is consolidating to Europe.',
    },
    {
      key: 'mls_gables1406', mls: 'A11615590', status: 'active', agent: MW, dom: 19,
      street: '1406 Valencia Ridge Road', neighborhood: 'Coral Gables', propertyType: 'single_family', style: 'Mediterranean Revival', family: 'Mediterranean',
      listPrice: 4795000, beds: 5, bathsFull: 4, bathsHalf: 1, sqft: 5200, lotSqft: 14800, yearBuilt: 1926, yearRenovated: 2019, stories: 2, garage: 2,
      views: ['garden'], amenities: ['pool', 'generator', 'summer_kitchen'], taxAnnual: 71000, photos: 5,
      headline: '1926 Gables Mediterranean, walk to school and the Biltmore',
      description: 'A 1926 original with a loggia, barrel ceilings and a 2019 kitchen, on a canopy street a short walk from two of the Gables’ best schools. Pool garden with a summer kitchen; two upstairs offices.',
    },
    {
      key: 'mls_gables211', mls: 'A11594478', status: 'active', agent: PP, dom: 44,
      street: '211 Casa Bonita Way', neighborhood: 'Coral Gables', propertyType: 'single_family', style: 'Spanish Revival', family: 'Spanish Revival',
      listPrice: 6250000, beds: 6, bathsFull: 5, bathsHalf: 1, sqft: 6400, lotSqft: 17000, yearBuilt: 1931, yearRenovated: 2021, stories: 2, garage: 2,
      views: ['garden', 'pool'], amenities: ['pool', 'guest_house', 'generator', 'wine_room'], taxAnnual: 93000, photos: 5,
      headline: 'Spanish Revival with guest house on a double lot',
      description: 'A 1931 Spanish Revival on a double lot with a separate guest house, a vaulted great room and a wine room carved from the old coal cellar. Renovated in 2021 without losing a single arch.',
    },
    {
      key: 'mls_gablesestates8', mls: 'A11510333', status: 'active', agent: GK, dom: 132,
      street: '8 Pelican Bight Road', neighborhood: 'Gables Estates', propertyType: 'estate', style: 'Contemporary', family: 'Contemporary',
      listPrice: 19800000, drop: { from: 20900000, daysAgo: 44, earlier: [{ from: 22500000, to: 20900000, daysAgo: 97 }] },
      beds: 7, bathsFull: 8, bathsHalf: 2, sqft: 10500, lotSqft: 56628, yearBuilt: 2012, stories: 2, garage: 4,
      waterfront: 'bayfront', frontage: 210, dock: 110, views: ['bay'], amenities: ['pool', 'dock', 'boat_lift', 'gated', 'guard_gated', 'guest_house', 'wine_room', 'gym', 'generator', 'elevator'],
      taxAnnual: 288000, photos: 5,
      headline: 'Gables Estates contemporary with 210 ft on the bay',
      description: 'A 1.3-acre bayfront in the guard-gated enclave, with a 110-ft dock, an elevator and a guest house by the water. Listed in spring at $22.5M and reduced twice — the comp every Gables Estates seller is watching.',
    },
    {
      key: 'mls_grove3270', mls: 'A11618021', status: 'active', agent: PP, dom: 12,
      street: '3270 Kumquat Hammock Lane', neighborhood: 'Coconut Grove', propertyType: 'single_family', style: 'Tropical Modern', family: 'Tropical Modern',
      listPrice: 5350000, beds: 5, bathsFull: 5, bathsHalf: 1, sqft: 4800, lotSqft: 11000, yearBuilt: 2017, stories: 2, garage: 2,
      views: ['garden', 'pool'], amenities: ['pool', 'smart_home', 'generator', 'summer_kitchen'], taxAnnual: 79000, photos: 5,
      headline: 'Tropical modern on a fenced lot, blocks from Biscayne Prep',
      description: 'Under a canopy of mango and oak, a 2017 tropical modern with a fully fenced pool yard, two home offices and a guest suite downstairs. Bike to school, the village and the sailing club.',
    },
    {
      key: 'mls_kb355', mls: 'A11621187', status: 'coming_soon', agent: HL, dom: 0,
      street: '355 Harbor Light Drive', neighborhood: 'Key Biscayne', propertyType: 'single_family', style: 'Modern', family: 'Modern',
      listPrice: 6950000, beds: 5, bathsFull: 5, bathsHalf: 1, sqft: 5100, lotSqft: 13000, yearBuilt: 2019, stories: 2, garage: 2,
      views: ['garden'], amenities: ['pool', 'generator', 'smart_home', 'elevator'], taxAnnual: 104000, photos: 4,
      headline: 'Coming soon: elevator modern near the Key Biscayne beach club',
      description: 'A 2019 modern with an elevator, a deep covered terrace and a heated saltwater pool, a short bike ride to the beach. Goes live next week.',
    },
    {
      key: 'mls_pinecrest6205', mls: 'A11570802', status: 'active', agent: PP, dom: 88,
      street: '6205 Old Banyan Road', neighborhood: 'Pinecrest', propertyType: 'single_family', style: 'Contemporary', family: 'Contemporary',
      listPrice: 4450000, drop: { from: 4750000, daysAgo: 5 }, beds: 5, bathsFull: 5, bathsHalf: 1, sqft: 5300, lotSqft: 39200, yearBuilt: 2010, yearRenovated: 2022, stories: 2, garage: 3,
      views: ['garden', 'pool'], amenities: ['pool', 'generator', 'summer_kitchen', 'gated'], taxAnnual: 66000, photos: 5,
      headline: 'Pinecrest pool home on 0.9 acre — reduced $300K',
      description: 'A gated contemporary on nearly an acre with a resort pool, a play lawn and a three-car garage. Freshly reduced; sellers are relocating for work and the house is vacant and easy to show.',
    },
    {
      key: 'mls_vela4102', mls: 'A11619913', status: 'active', agent: HL, dom: 15,
      street: '60 Vela Bay Walk', unitNumber: '4102', buildingName: 'Vela Brickell', neighborhood: 'Brickell', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary',
      listPrice: 2350000, beds: 2, bathsFull: 2, bathsHalf: 1, sqft: 1750, yearBuilt: 2019, views: ['bay', 'skyline'], amenities: CONDO_AM, hoaFee: 2400, taxAnnual: 35000, photos: 4,
      headline: '41st-floor Vela two-bedroom with bay views',
      description: 'A high-floor two-bedroom with a bay-facing terrace and Italian cabinetry. Two-bedrooms in the building lease for $11–13K a month.',
    },
    {
      key: 'mls_aqua2908', mls: 'A11622406', status: 'active', agent: GK, dom: 9,
      street: '2900 Lumen Bay Drive', unitNumber: '2908', buildingName: 'Aqua Lumen Edgewater', neighborhood: 'Edgewater', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary',
      listPrice: 2890000, beds: 3, bathsFull: 3, bathsHalf: 1, sqft: 2250, yearBuilt: 2021, waterfront: 'bayfront', views: ['bay'], amenities: CONDO_AM, hoaFee: 2900, taxAnnual: 42000, photos: 4,
      headline: 'Edgewater three-bedroom with a 40-ft gallery wall',
      description: 'A bayfront three-bedroom with an unusually long, uninterrupted wall in the living room and gallery lighting already wired. Walk to the Design District.',
    },
    {
      key: 'mls_atelier6c', mls: 'A11576644', status: 'active', agent: MW, dom: 52,
      street: '41 Atelier Row', unitNumber: '6C', buildingName: 'Atelier 41 Residences', neighborhood: 'Edgewater', propertyType: 'condo', style: 'Industrial Loft', family: 'Contemporary',
      listPrice: 2150000, beds: 2, bathsFull: 2, bathsHalf: 1, sqft: 1900, yearBuilt: 2018, views: ['city'], amenities: ['gym', 'concierge', 'rooftop_terrace'], hoaFee: 1900, taxAnnual: 31000, photos: 4,
      headline: 'Design District loft with 13-ft ceilings',
      description: 'Board-formed concrete, 13-ft ceilings and a den that works as a studio. One block from the Design District galleries.',
    },
    {
      key: 'mls_lasolas48', mls: 'A11558207', status: 'active', agent: OW, dom: 101,
      street: '48 Coral Key Isle', neighborhood: 'Las Olas', propertyType: 'single_family', style: 'Modern', family: 'Modern',
      listPrice: 6400000, drop: { from: 6900000, daysAgo: 1 }, beds: 5, bathsFull: 5, bathsHalf: 1, sqft: 5600, lotSqft: 11500, yearBuilt: 2018, stories: 3, garage: 2,
      waterfront: 'canal', frontage: 100, dock: 100, views: ['water'], amenities: ['pool', 'dock', 'boat_lift', 'elevator', 'generator', 'smart_home'],
      taxAnnual: 94000, photos: 5,
      headline: 'Las Olas Isles deep water, no fixed bridges — reduced $500K',
      description: 'A wide-water lot on the Las Olas Isles with 100 ft of new seawall, a 100-ft dock and a three-stop elevator. Ten minutes to the inlet with no fixed bridges. Reduced yesterday.',
    },
    {
      key: 'mls_palmbeach240', mls: 'RX-11023817', status: 'active', agent: PB, dom: 61,
      street: '240 Seabreeze Mews', neighborhood: 'Palm Beach', propertyType: 'single_family', style: 'British Colonial', family: 'Colonial',
      listPrice: 12500000, beds: 5, bathsFull: 5, bathsHalf: 2, sqft: 6000, lotSqft: 17400, yearBuilt: 1998, yearRenovated: 2020, stories: 2, garage: 2,
      views: ['garden', 'pool'], amenities: ['pool', 'guest_house', 'generator', 'summer_kitchen'], taxAnnual: 152000, photos: 5,
      headline: 'In-town Palm Beach, two blocks to Worth Avenue',
      description: 'A British Colonial in the heart of town with a loggia, a pool cottage and walled gardens. Walk to the beach, Worth Avenue and the tennis club; renovated in 2020 with a new kitchen and impact glass.',
    },
    {
      key: 'mls_jupiter9', mls: 'RX-10998452', status: 'active', agent: PB, dom: 140,
      street: '9 Plover Point Lane', neighborhood: 'Jupiter Island', propertyType: 'single_family', style: 'British Colonial', family: 'Colonial',
      listPrice: 8250000, beds: 5, bathsFull: 5, bathsHalf: 1, sqft: 5800, lotSqft: 69700, yearBuilt: 1989, yearRenovated: 2016, stories: 2, garage: 3,
      waterfront: 'intracoastal', frontage: 150, dock: 100, views: ['intracoastal', 'sunset'], amenities: ['pool', 'dock', 'boat_lift', 'guest_house', 'generator'],
      taxAnnual: 101000, photos: 5,
      headline: 'Jupiter Island sunset-side retreat with deep-water dock',
      description: 'On 1.6 acres along the Intracoastal with 150 ft of water and a 100-ft dock, minutes from the island club’s golf course. Low-key, private and very Jupiter Island.',
    },
  ];
};
