// Own listings, pocket/coming-soon, whispers and new-development units.
// Compact fields: dom = days on market, drop = {from, daysAgo, earlier:[{from,to,daysAgo}]},
// agent = [listAgentName, listOfficeName], owner = client key.
const ME = ['Alex Morgan', 'Harbor & Key Realty'];
const VIDAL = ['Casa Palmera Sales Gallery', 'Vidal Urban'];

module.exports = function ownListings() {
  return [
    // ── My Listings (own)
    {
      key: 'own_sunset', src: 'own', origin: 'own', status: 'active', owner: 'graham', agent: ME, dom: 9,
      street: '128 Sunset Drive', neighborhood: 'Sunset Islands', propertyType: 'single_family', style: 'Contemporary', family: 'Modern',
      listPrice: 18750000, beds: 6, bathsFull: 7, bathsHalf: 2, sqft: 8450, lotSqft: 18750, yearBuilt: 2018, yearRenovated: 2023, stories: 2, garage: 3,
      waterfront: 'bayfront', frontage: 105, dock: 90, views: ['bay', 'skyline', 'sunset'],
      amenities: ['pool', 'dock', 'boat_lift', 'elevator', 'gated', 'wine_room', 'home_theater', 'gym', 'summer_kitchen', 'generator', 'smart_home', 'rooftop_terrace'],
      taxAnnual: 268000, photos: 6, featureSheet: true,
      headline: 'Sunset Islands modern with 105 ft of open-bay frontage',
      description: 'A glass-and-limestone modern on the widest stretch of open water on Sunset Islands, finished in 2023 with a new 90-ft dock and 30,000-lb lift. The main level opens on three sides to a 75-ft infinity pool and the downtown skyline at dusk. Upstairs, the primary suite has its own terrace, two dressing rooms and a spa bath in book-matched Calacatta; the roof deck seats twenty for sunset.',
    },
    {
      key: 'own_lagorce', src: 'own', origin: 'own', status: 'active', owner: 'simone', agent: ME, dom: 34,
      street: '2741 Fairway Isle Drive', neighborhood: 'La Gorce', propertyType: 'single_family', style: 'Mediterranean Revival', family: 'Mediterranean',
      listPrice: 12900000, drop: { from: 13900000, daysAgo: 4 }, beds: 6, bathsFull: 6, bathsHalf: 1, sqft: 7200, lotSqft: 22500, yearBuilt: 1928, yearRenovated: 2021, stories: 2, garage: 2,
      waterfront: 'canal', frontage: 120, dock: 60, views: ['golf', 'water', 'garden'],
      amenities: ['pool', 'dock', 'guest_house', 'gated', 'wine_room', 'summer_kitchen', 'generator', 'staff_quarters'],
      taxAnnual: 191000, photos: 6, featureSheet: true,
      headline: '1928 La Gorce Mediterranean, re-imagined — now $12.9M',
      description: 'A 1928 Mediterranean Revival with its pecky-cypress ceilings, hand-painted tile and arched loggia intact, rebuilt underneath in 2021 with impact glass, new systems and a whole-house generator. The two-story guest house sits over a four-car motor court, and 120 ft of waterway frontage looks across to the La Gorce fairways. Open house this Sunday, 1–4.',
    },
    {
      key: 'own_mangrove', src: 'own', origin: 'own', status: 'under_contract', owner: 'beatriz', agent: ME, dom: 41,
      street: '3417 Mangrove Point Road', neighborhood: 'Coconut Grove', propertyType: 'single_family', style: 'Tropical Modern', family: 'Tropical Modern',
      listPrice: 7650000, beds: 5, bathsFull: 5, bathsHalf: 1, sqft: 5600, lotSqft: 15200, yearBuilt: 2016, stories: 3, garage: 2,
      waterfront: null, views: ['garden', 'bay'], amenities: ['pool', 'rooftop_terrace', 'smart_home', 'generator', 'summer_kitchen', 'gym'],
      taxAnnual: 112000, photos: 5,
      headline: 'Architect-owned Tropical Modern under the Grove canopy',
      description: 'Designed by its architect-owner around a 100-year-old oak, the house wraps a courtyard pool in ipe, board-formed concrete and floor-to-ceiling glass. A rooftop terrace catches the bay breeze and a slice of Biscayne Bay over the treetops. Walk to the village, the sailing club and three of the Grove’s best schools.',
    },
    {
      key: 'own_solace', src: 'own', origin: 'own', status: 'sold', owner: 'adrian', agent: ME, soldDeal: 'kessler',
      street: '9001 Collins Avenue', unitNumber: '803', buildingName: 'Solace Surfside', neighborhood: 'Surfside', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary',
      listPrice: 4150000, closePrice: 3950000, beds: 3, bathsFull: 3, bathsHalf: 1, sqft: 2650, yearBuilt: 2017, waterfront: 'oceanfront', views: ['ocean'],
      amenities: ['pool', 'gym', 'spa', 'concierge', 'private_beach'], hoaFee: 4900, taxAnnual: 61000, photos: 4,
      headline: 'Direct-ocean three-bedroom at Solace Surfside',
      description: 'A flow-through residence with 12-ft sliders to the ocean and a private elevator vestibule. Beach service, a 25-meter lap pool and a quiet, twenty-two-residence building. Sold in a multiple-offer week.',
    },
    {
      key: 'own_oldcutler', src: 'own', origin: 'own', status: 'sold', owner: 'jonah', agent: ME, soldDeal: 'feld',
      street: '6940 Old Cutler Bend', neighborhood: 'Pinecrest', propertyType: 'single_family', style: 'British Colonial', family: 'Colonial',
      listPrice: 5850000, closePrice: 5600000, beds: 6, bathsFull: 6, bathsHalf: 1, sqft: 6800, lotSqft: 52272, yearBuilt: 2008, yearRenovated: 2020, stories: 2, garage: 3,
      views: ['garden', 'pool'], amenities: ['pool', 'tennis', 'guest_house', 'generator', 'summer_kitchen', 'gated'], taxAnnual: 83000, photos: 5,
      headline: 'Gated British Colonial on 1.2 acres with lighted tennis',
      description: 'Wide verandas, heart-pine floors and a lighted tennis court on 1.2 gated acres off Old Cutler. The pool cabana doubles as a guest suite. Sold to a relocating family two weeks after the first showing.',
    },
    {
      key: 'own_aurelia', src: 'own', origin: 'own', status: 'sold', owner: 'olivia', agent: ME, soldDeal: 'marlow',
      street: '1201 Brickell Bay Drive', unitNumber: 'PH5', buildingName: 'Aurelia Brickell', neighborhood: 'Brickell', propertyType: 'penthouse', style: 'Contemporary', family: 'Contemporary',
      listPrice: 4350000, closePrice: 4100000, beds: 4, bathsFull: 4, bathsHalf: 1, sqft: 4300, yearBuilt: 2019, views: ['bay', 'skyline'],
      amenities: ['rooftop_terrace', 'gym', 'spa', 'concierge', 'elevator'], hoaFee: 6800, taxAnnual: 64000, photos: 4,
      headline: 'Brickell penthouse with a 1,400-sq-ft sky terrace',
      description: 'Corner penthouse with private elevator, 11-ft ceilings and a 1,400-sq-ft terrace over Biscayne Bay. Sold furnished to a cash buyer.',
    },
    {
      key: 'own_aria1402', src: 'own', origin: 'own', status: 'active', owner: 'lydia', agent: ME, dom: 63,
      street: '10201 Collins Avenue', unitNumber: '1402', buildingName: 'The Aria at Bal Harbour', neighborhood: 'Bal Harbour', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary',
      listPrice: 6450000, drop: { from: 6950000, daysAgo: 6, earlier: [{ from: 7250000, to: 6950000, daysAgo: 31 }] },
      beds: 3, bathsFull: 3, bathsHalf: 1, sqft: 3100, yearBuilt: 2016, waterfront: 'oceanfront', views: ['ocean', 'intracoastal'],
      amenities: ['pool', 'gym', 'spa', 'concierge', 'private_beach', 'elevator'], hoaFee: 6450, taxAnnual: 98000, photos: 5,
      headline: 'The Aria 02 line — one-level oceanfront living, now $6.45M',
      description: 'The coveted 02 line: a single-level, east-west residence with ocean sunrises from the living room and Intracoastal sunsets from the kitchen. Private elevator entry, 10-ft ceilings and a 600-sq-ft ocean terrace. Estate-owned and priced to move; the building has full beach service and a 24-hour concierge.',
    },
    {
      key: 'own_sabal', src: 'own', origin: 'own', status: 'withdrawn', owner: 'imogen', agent: ME, dom: 140,
      street: '4 Sabal Cay', neighborhood: 'Coconut Grove', propertyType: 'single_family', style: 'Spanish Revival', family: 'Spanish Revival',
      listPrice: 5950000, beds: 5, bathsFull: 4, bathsHalf: 1, sqft: 4900, lotSqft: 12000, yearBuilt: 1937, yearRenovated: 2015, stories: 2, garage: 1,
      views: ['garden'], amenities: ['pool', 'guest_house', 'generator'], taxAnnual: 87000, photos: 4,
      headline: '1937 Spanish Revival on a private cul-de-sac',
      description: 'Barrel-tile roof, original Cuban tile and a coral-rock courtyard on a quiet Grove cul-de-sac. Withdrawn — the owner decided to lease it.',
    },

    // ── Pocket & coming soon
    {
      key: 'pk_seagrape', src: 'pocket', origin: 'pocket', status: 'coming_soon', agent: ME, dom: 0, slug: true,
      street: '411 Sea Grape Way', neighborhood: 'Key Biscayne', propertyType: 'single_family', style: 'Tropical Modern', family: 'Tropical Modern',
      listPrice: 9250000, beds: 6, bathsFull: 6, bathsHalf: 1, sqft: 6900, lotSqft: 20000, yearBuilt: 2020, stories: 2, garage: 2,
      waterfront: 'bayfront', frontage: 80, dock: 70, views: ['bay', 'sunset'], amenities: ['pool', 'dock', 'boat_lift', 'generator', 'smart_home', 'summer_kitchen', 'elevator'],
      taxAnnual: 139000, photos: 5,
      headline: 'Coming soon: Key Biscayne bayfront with sunset dock',
      description: 'A 2020 tropical modern on the bay side of the island, built to the newest code with an elevator, whole-house generator and a 70-ft dock facing west over the water. Owners are relocating to Lisbon and would rather sell quietly before photos go live.',
    },
    {
      key: 'pk_star', src: 'pocket', origin: 'pocket', status: 'off_market', agent: ME, hideAddress: true, slug: true,
      title: 'Star Island · private offering', street: '6 Star Island Crescent', neighborhood: 'Star Island', propertyType: 'estate', style: 'Mediterranean Revival', family: 'Mediterranean',
      listPrice: 38500000, beds: 9, bathsFull: 10, bathsHalf: 3, sqft: 16400, lotSqft: 47900, yearBuilt: 1931, yearRenovated: 2019, stories: 3, garage: 4,
      waterfront: 'bayfront', frontage: 180, dock: 140, views: ['bay', 'skyline', 'sunset'],
      amenities: ['pool', 'dock', 'boat_lift', 'elevator', 'gated', 'guard_gated', 'guest_house', 'wine_room', 'home_theater', 'gym', 'spa', 'summer_kitchen', 'generator', 'smart_home', 'staff_quarters', 'tennis'],
      taxAnnual: 590000, photos: 6,
      headline: 'Guard-gated Star Island estate — shown by appointment only',
      description: 'A 1931 Mediterranean Revival estate restored down to the hand-carved coquina, on 1.1 acres with 180 ft of deep water and a 140-ft dock that takes a serious yacht. Separate staff residence, tennis and a 1,200-bottle cellar. The family will consider qualified buyers only; no signage, no MLS.',
    },
    {
      key: 'pk_sunsetII', src: 'pocket', origin: 'pocket', status: 'coming_soon', agent: ME, slug: true,
      street: '1740 Sunset Isle Way', neighborhood: 'Sunset Islands', propertyType: 'single_family', style: 'Tropical Modern', family: 'Tropical Modern',
      listPrice: 11200000, beds: 5, bathsFull: 6, bathsHalf: 1, sqft: 6300, lotSqft: 13500, yearBuilt: 2015, yearRenovated: 2024, stories: 2, garage: 2,
      waterfront: 'bayfront', frontage: 75, dock: 60, views: ['bay', 'skyline'], amenities: ['pool', 'dock', 'rooftop_terrace', 'generator', 'smart_home', 'summer_kitchen'],
      taxAnnual: 166000, photos: 5,
      headline: 'Coming soon on Sunset Island II — renovated 2024',
      description: 'Teak, travertine and a new glass envelope after a 2024 renovation, with a rooftop terrace that looks straight at the downtown skyline. Shorter dock than 128 Sunset Drive at a much friendlier number.',
    },
    {
      key: 'pk_aqua', src: 'pocket', origin: 'pocket', status: 'off_market', agent: ME, hideAddress: true, slug: true,
      title: 'Edgewater penthouse · off-market', street: '2900 NE 7th Avenue', unitNumber: 'PH-A', buildingName: 'Aqua Lumen Edgewater', neighborhood: 'Edgewater', propertyType: 'penthouse', style: 'Contemporary', family: 'Contemporary',
      listPrice: 4600000, beds: 3, bathsFull: 3, bathsHalf: 1, sqft: 3800, yearBuilt: 2021, views: ['bay', 'skyline'], amenities: ['rooftop_terrace', 'pool', 'gym', 'concierge', 'elevator'],
      hoaFee: 5200, taxAnnual: 69000, photos: 4,
      headline: 'Off-market Edgewater penthouse with private plunge pool',
      description: 'A full-floor-feel penthouse with a private rooftop plunge pool and a straight shot of the bay. The seller is a fund manager moving to Nashville and wants no showings until a qualified buyer is lined up.',
    },
    {
      key: 'pk_equestrian', src: 'pocket', origin: 'pocket', status: 'coming_soon', agent: ME, slug: true,
      street: '9850 Sabal Ranch Road', neighborhood: 'Pinecrest', propertyType: 'estate', style: 'British Colonial', family: 'Colonial',
      listPrice: 7900000, beds: 6, bathsFull: 6, bathsHalf: 2, sqft: 8100, lotSqft: 87120, yearBuilt: 2004, yearRenovated: 2022, stories: 2, garage: 4,
      views: ['garden', 'pool'], amenities: ['pool', 'tennis', 'guest_house', 'gated', 'generator', 'staff_quarters', 'summer_kitchen'],
      taxAnnual: 117000, photos: 5,
      headline: 'Two gated acres in Pinecrest — barn, paddock and tennis',
      description: 'Two acres behind a gated allée of royal palms, with a four-stall barn, paddock, tennis and a guest house. The main house was opened up in 2022 with a 30-ft family room and a chef’s kitchen that leads to a covered summer kitchen.',
    },
    {
      key: 'pk_ellery', src: 'pocket', origin: 'pocket', status: 'off_market', agent: ME, slug: true,
      street: '1300 Brickell Avenue', unitNumber: '3901', buildingName: 'The Ellery Brickell', neighborhood: 'Brickell', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary',
      listPrice: 3300000, beds: 3, bathsFull: 3, bathsHalf: 1, sqft: 2400, yearBuilt: 2020, views: ['bay', 'skyline'], amenities: ['pool', 'gym', 'spa', 'concierge'],
      hoaFee: 3600, taxAnnual: 48000, photos: 4,
      headline: 'High-floor Ellery corner, tenant-friendly',
      description: 'A 39th-floor corner with bay views from every room, currently leased at $15,500 a month through May. A clean, quiet sale for an investor who wants income on day one.',
    },

    // ── Whispers
    {
      key: 'wh_goldenbeach', src: 'whisper', origin: 'whisper', status: 'off_market', hideAddress: true,
      title: 'Golden Beach oceanfront · owner may sell quietly', street: '389 Seagrape Shore Drive', neighborhood: 'Golden Beach', propertyType: 'estate', style: 'Contemporary', family: 'Contemporary',
      priceGuide: 34000000, eta: 'after the holidays', whisperSource: 'owner', confidence: { price: 0.6, timing: 0.5, specs: 0.8, note: 'Owner told me directly at a dinner; wants no agents through the door until January.' },
      beds: 7, bathsFull: 8, bathsHalf: 2, sqft: 9800, lotSqft: 26000, yearBuilt: 2012, waterfront: 'oceanfront', frontage: 100, views: ['ocean', 'sunrise'],
      amenities: ['pool', 'private_beach', 'gated', 'staff_quarters', 'gym', 'spa', 'wine_room', 'elevator', 'generator'], photos: 4,
      headline: 'Owner-quiet oceanfront in Golden Beach',
      description: 'A 2012 contemporary on 100 ft of beach with 12-ft ceilings and staff quarters over the garage. The owner is relocating to Monaco and will entertain one or two serious buyers before listing.',
    },
    {
      key: 'wh_indiancreek', src: 'whisper', origin: 'whisper', status: 'off_market', hideAddress: true,
      title: 'Indian Creek compound · may trade in spring', street: 'Indian Creek Island Road', neighborhood: 'Indian Creek', propertyType: 'estate', style: 'Contemporary', family: 'Contemporary',
      priceGuide: 58000000, eta: 'spring', whisperSource: 'broker_open', confidence: { price: 0.4, timing: 0.35, specs: 0.7, note: 'Heard at the Gables Estates broker open from two agents independently.' },
      beds: 10, bathsFull: 11, bathsHalf: 3, sqft: 18500, lotSqft: 91476, yearBuilt: 2014, waterfront: 'bayfront', frontage: 200, dock: 150, views: ['bay', 'golf', 'sunset'],
      amenities: ['pool', 'dock', 'guard_gated', 'gated', 'guest_house', 'staff_quarters', 'tennis', 'wine_room', 'gym', 'spa', 'home_theater', 'generator', 'elevator'], photos: 4,
      headline: 'Indian Creek waterfront compound',
      description: 'Two acres on the island with 200 ft on the bay, a 150-ft dock and a separate guest pavilion. Family is reportedly weighing a sale after a liquidity event; nothing is signed.',
    },
    {
      key: 'wh_cpphase2', src: 'whisper', origin: 'whisper', status: 'off_market', developmentName: 'Casa Palmera Residences',
      title: 'Casa Palmera Phase II · penthouse release', street: '3100 S Bayshore Drive', buildingName: 'Casa Palmera Residences', neighborhood: 'Coconut Grove', propertyType: 'penthouse', style: 'Tropical Modern', family: 'Tropical Modern',
      priceGuide: 11500000, eta: 'January', whisperSource: 'developer', confidence: { price: 0.75, timing: 0.6, specs: 0.85, note: 'Lorenzo Vidal shared the draft price sheet over lunch — not for distribution.' },
      beds: 4, bathsFull: 5, bathsHalf: 1, sqft: 5400, yearBuilt: 2029, views: ['bay', 'skyline'], amenities: ['rooftop_terrace', 'pool', 'gym', 'spa', 'concierge', 'elevator'], photos: 4,
      headline: 'Phase II penthouses — priority list only',
      description: 'Two penthouses crown Phase II, each with a private rooftop pool and 1,800 sq ft of terraces over the bay. Pricing goes to the priority list first; deposits are 10% to reserve, 20% at contract.',
    },
    {
      key: 'wh_fisher', src: 'whisper', origin: 'whisper', status: 'off_market', hideAddress: true,
      title: 'Fisher Island villa · estate sale coming', street: 'Fisher Island Drive', neighborhood: 'Fisher Island', propertyType: 'villa', style: 'Mediterranean Revival', family: 'Mediterranean',
      priceGuide: 14000000, eta: '60 days', whisperSource: 'agent', confidence: { price: 0.55, timing: 0.7, specs: 0.6, note: 'Probate attorney contact; heirs want one buyer, no open houses.' },
      beds: 5, bathsFull: 5, bathsHalf: 1, sqft: 6100, yearBuilt: 1998, yearRenovated: 2016, waterfront: 'oceanfront', views: ['ocean'],
      amenities: ['pool', 'gated', 'guard_gated', 'spa', 'generator'], photos: 4,
      headline: 'Ocean villa on Fisher Island, estate sale',
      description: 'A two-story villa steps from the beach club with a private pool garden. The heirs want a single, discreet buyer within sixty days.',
    },

    // ── New development (pre-construction)
    ...[
      { key: 'dev_cp1803', unit: '1803', floor: 18, line: '03', price: 3950000, beds: 3, full: 3, half: 1, sqft: 2700, hoa: 3900 },
      { key: 'dev_cp2104', unit: '2104', floor: 21, line: '04', price: 4650000, beds: 3, full: 3, half: 1, sqft: 3050, hoa: 4400 },
      { key: 'dev_cp2602', unit: '2602', floor: 26, line: '02', price: 6200000, beds: 4, full: 4, half: 1, sqft: 3900, hoa: 5600 },
    ].map((u, i) => ({
      key: u.key, src: 'mls', origin: 'development', status: 'active', agent: VIDAL, dom: 120 - i * 20, developmentName: 'Casa Palmera Residences',
      street: '3100 S Bayshore Drive', unitNumber: u.unit, buildingName: 'Casa Palmera Residences', neighborhood: 'Coconut Grove', floor: u.floor, unitLine: u.line,
      propertyType: 'condo', propertySubType: 'pre_construction', style: 'Tropical Modern', family: 'Tropical Modern',
      listPrice: u.price, beds: u.beds, bathsFull: u.full, bathsHalf: u.half, sqft: u.sqft, yearBuilt: 2028, views: ['bay', 'skyline'],
      amenities: ['pool', 'gym', 'spa', 'concierge', 'rooftop_terrace'], hoaFee: u.hoa, photos: 4,
      headline: `Casa Palmera Residence ${u.unit} · pre-construction, delivering 2028`,
      description: [
        `Line ${u.line} on the ${u.floor}th floor faces southeast over Biscayne Bay with a 10-ft-deep terrace off every room. Deposits: 10% at reservation, 20% at contract, 10% at groundbreaking and 10% at top-off; balance at closing.`,
        `A ${u.beds}-bedroom on floor ${u.floor} with a wet-bar den and a summer-kitchen terrace. Finish selections open next spring; developer is Vidal Urban, architecture by a Grove-based studio known for shade-first design.`,
        `The ${u.floor}th-floor ${u.beds}-bedroom is the largest Phase I plan still available, with a corner great room and a private elevator foyer. Phase I is 82% reserved.`,
      ][i],
    })),
    {
      key: 'dev_solenne7b', src: 'mls', origin: 'development', status: 'active', agent: ['Solenne Sales Team', 'Solenne Bay Harbor'], dom: 85, developmentName: 'Solenne Bay Harbor',
      street: '1080 Kane Concourse', unitNumber: '7B', buildingName: 'Solenne Bay Harbor', neighborhood: 'Bay Harbor Islands', floor: 7, unitLine: 'B',
      propertyType: 'condo', propertySubType: 'pre_construction', style: 'Contemporary', family: 'Contemporary',
      listPrice: 2450000, beds: 2, bathsFull: 2, bathsHalf: 1, sqft: 1850, yearBuilt: 2027, waterfront: 'bayfront', views: ['bay'],
      amenities: ['pool', 'gym', 'concierge', 'dock'], hoaFee: 2600, photos: 3,
      headline: 'Boutique bayfront two-bedroom with a deeded boat slip',
      description: 'A 34-residence boutique building on the Bay Harbor waterway; 7B comes with a deeded 40-ft slip. Short-term rentals are allowed with a 30-day minimum, which is why investors are circling.',
    },
  ];
};
