// PortfolioProperty rows (the client's "garage") and BuyerSearch criteria.
// Properties tied to a closed deal take purchase/sale price + date from it
// (deal + role 'bought' | 'sold'); others give bought: [offsetDays, yearsAgo].
module.exports = function buildPortfolio(ctx) {
  const o = ctx.off;
  const SF = 'single_family';
  const props = [
    // Harold & June Brennan
    { key: 'pp_brennan_kb', client: 'harold', relationship: 'owns', occupancy: 'primary', nickname: 'The Key Biscayne house', deal: 'brennan2021', role: 'bought',
      street: '260 Harbor Palm Lane', neighborhood: 'Key Biscayne', propertyType: SF, style: 'Contemporary', family: 'Contemporary', beds: 6, baths: 6.5, sqft: 5400, lotSqft: 12500, yearBuilt: 2005, stories: 2, garage: 2,
      views: ['garden', 'pool'], amenities: ['pool', 'generator', 'summer_kitchen'], estValue: 7800000, valueSource: 'cma', titleHolding: 'joint',
      lenderName: 'Meridian Coast Private Bank', mortgageBalance: 2950000, mortgageRate: 3.125, loanType: 'arm', loanResetAt: ctx.at(o.haroldReset, 12), loanYears: 30, taxAnnual: 118000,
      thinkingOfSelling: true, sellSignals: [
        { signal: 'downsizing', strength: 0.8, quote: 'We don’t need six bedrooms for two people and a golden retriever’s ghost.', source: 'call' },
        { signal: 'arm_reset', strength: 0.7, quote: 'What does our payment look like when the rate resets?', source: 'text' },
        { signal: 'one_level', strength: 0.6, quote: 'June can’t do the stairs anymore after the knee.', source: 'note' },
      ], photos: 5, notes: '5/1 ARM from the 2021 purchase. Kitchen redone 2022; roof 2019.' },
    { key: 'pp_brennan_highlands', client: 'harold', relationship: 'owns', occupancy: 'second_home', nickname: 'Highlands, NC cabin', street: '44 Laurel Knob Trail', city: 'Highlands', state: 'NC', zip: '28741', market: 'Highlands NC',
      propertyType: SF, style: 'Mountain Craftsman', family: 'Craftsman', beds: 4, baths: 3.5, sqft: 3600, lotAcres: 2.2, yearBuilt: 1999, bought: [140, 14], purchasePrice: 1250000, estValue: 2100000, valueSource: 'avm', titleHolding: 'joint', loanType: 'cash', photos: 3 },
    { key: 'pp_brennan_aria', client: 'harold', relationship: 'watching', nickname: 'The one June likes — Aria 1402', listing: 'own_aria1402', source: 'listing_link' },

    // Charles & Margaret Lowell
    { key: 'pp_lowell_estate', client: 'charles', relationship: 'owns', occupancy: 'primary', nickname: 'Coral Isle Way estate', street: '11 Coral Isle Way', neighborhood: 'Gables Estates', subdivision: 'Gables Estates',
      propertyType: 'estate', style: 'Anglo-Caribbean', family: 'Colonial', beds: 7, baths: 8.5, sqft: 11200, lotSqft: 61000, lotAcres: 1.4, yearBuilt: 1997, stories: 2, garage: 4,
      waterfront: 'bayfront', frontage: 245, dock: 100, views: ['bay', 'sunset'], amenities: ['pool', 'dock', 'boat_lift', 'gated', 'guard_gated', 'guest_house', 'wine_room', 'tennis', 'generator', 'staff_quarters'],
      bought: [-110, 17], purchasePrice: 6100000, estValue: 21500000, valueSource: 'cma', titleHolding: 'trust', loanType: 'cash', taxAnnual: 305000,
      thinkingOfSelling: true, sellSignals: [
        { signal: 'empty_nest', strength: 0.8, quote: 'The boat hasn’t left the dock since spring.', source: 'call' },
        { signal: 'one_level', strength: 0.7, quote: 'Margaret wants one floor, no stairs.', source: 'call' },
        { signal: 'interviewing_agents', strength: 0.9, quote: 'We’re talking to two other firms, so bring your A game.', source: 'call' },
      ], photos: 6, notes: 'Held in the Lowell Family Trust — Eleanor Rios is trustee counsel.' },

    // Whitakers
    { key: 'pp_whitaker_sunset', client: 'graham', relationship: 'owns', occupancy: 'primary', nickname: '128 Sunset Drive', listing: 'own_sunset', street: '128 Sunset Drive', neighborhood: 'Sunset Islands',
      propertyType: SF, style: 'Contemporary', family: 'Modern', beds: 6, baths: 8, sqft: 8450, lotSqft: 18750, yearBuilt: 2018, stories: 2, garage: 3, waterfront: 'bayfront', frontage: 105, dock: 90,
      views: ['bay', 'skyline', 'sunset'], amenities: ['pool', 'dock', 'boat_lift', 'elevator', 'gated', 'wine_room', 'home_theater', 'gym'], bought: [70, 10], purchasePrice: 7900000,
      estValue: 18750000, valueSource: 'listing', titleHolding: 'joint', lenderName: 'Brightwater Private Bank', mortgageBalance: 3100000, mortgageRate: 2.875, loanType: 'fixed', loanYears: 30, taxAnnual: 268000, photos: 5,
      notes: 'Bought the original 1950s house in 2016, rebuilt 2018, refreshed 2023.' },

    // Delacroix, Ashcombe, Montoya, Hayes
    { key: 'pp_delacroix_paris', client: 'julien', relationship: 'owns', occupancy: 'second_home', nickname: 'Paris 7e apartment', city: 'Paris', state: null, market: 'Paris', propertyType: 'condo', style: 'Haussmann', family: 'Classical', beds: 3, baths: 2, sqft: 1900, yearBuilt: 1880, bought: [200, 8], purchasePrice: 2300000, estValue: 2650000, valueSource: 'manual', titleHolding: 'joint', loanType: 'cash', photos: 3 },
    { key: 'pp_ashcombe_tribeca', client: 'victoria', relationship: 'owns', occupancy: 'primary', nickname: 'Tribeca penthouse', city: 'New York', state: 'NY', zip: '10013', market: 'Manhattan', propertyType: 'penthouse', style: 'Loft', family: 'Contemporary', beds: 4, baths: 4.5, sqft: 6200, yearBuilt: 1910, bought: [90, 9], purchasePrice: 11500000, estValue: 16000000, valueSource: 'manual', titleHolding: 'llc', loanType: 'cash', photos: 3, notes: 'Listing with a Manhattan broker in January once Florida closes.' },
    { key: 'pp_ashcombe_southampton', client: 'victoria', relationship: 'owns', occupancy: 'second_home', nickname: 'Southampton beach house', city: 'Southampton', state: 'NY', zip: '11968', market: 'Hamptons', propertyType: SF, style: 'Shingle Style', family: 'Colonial', beds: 6, baths: 6.5, sqft: 7400, lotAcres: 2.0, yearBuilt: 2006, waterfront: 'oceanfront', bought: [30, 6], purchasePrice: 14000000, estValue: 19500000, valueSource: 'manual', titleHolding: 'llc', loanType: 'cash', photos: 3 },
    { key: 'pp_ashcombe_indiancreek', client: 'victoria', relationship: 'watching', nickname: 'Indian Creek compound (whisper)', listing: 'wh_indiancreek', source: 'described' },
    { key: 'pp_montoya_home', client: 'rafael', relationship: 'owns', occupancy: 'primary', nickname: 'Gables house', street: '1520 Alcazar Vista Way', neighborhood: 'Coral Gables', propertyType: SF, style: 'Mediterranean Revival', family: 'Mediterranean', beds: 5, baths: 5.5, sqft: 5600, lotSqft: 16000, yearBuilt: 1927, bought: [-30, 11], purchasePrice: 2400000, estValue: 5900000, valueSource: 'avm', titleHolding: 'joint', loanType: 'cash', photos: 4 },
    { key: 'pp_montoya_edgewater', client: 'rafael', relationship: 'owns', occupancy: 'investment', nickname: 'Aqua Lumen 1406 (rented)', street: '2900 Lumen Bay Drive', unit: '1406', buildingName: 'Aqua Lumen Edgewater', neighborhood: 'Edgewater', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 2, baths: 2.5, sqft: 1600, yearBuilt: 2021, bought: [-200, 5], purchasePrice: 1450000, estValue: 1950000, valueSource: 'avm', titleHolding: 'llc', loanType: 'cash', rentAmount: 9500, leaseEndsAt: ctx.at(210, 12), hoaMonthly: 2100, photos: 3 },
    { key: 'pp_montoya_brickell', client: 'rafael', relationship: 'owns', occupancy: 'investment', nickname: 'Vela 2802 (rented)', street: '60 Vela Bay Walk', unit: '2802', buildingName: 'Vela Brickell', neighborhood: 'Brickell', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 2, baths: 2.5, sqft: 1700, yearBuilt: 2019, bought: [-150, 6], purchasePrice: 1200000, estValue: 1650000, valueSource: 'avm', titleHolding: 'llc', loanType: 'cash', rentAmount: 8800, leaseEndsAt: ctx.at(260, 12), hoaMonthly: 2300, photos: 3 },
    { key: 'pp_hayes_indiancreek', client: 'sterling', relationship: 'owns', occupancy: 'primary', nickname: 'Indian Creek estate', neighborhood: 'Indian Creek', propertyType: 'estate', style: 'Contemporary', family: 'Contemporary', beds: 9, baths: 11, sqft: 17000, lotAcres: 1.9, yearBuilt: 2010, waterfront: 'bayfront', frontage: 190, dock: 160, amenities: ['pool', 'dock', 'guard_gated', 'staff_quarters', 'tennis', 'wine_room'], bought: [-60, 15], purchasePrice: 18000000, estValue: 48000000, valueSource: 'manual', titleHolding: 'trust', loanType: 'cash', photos: 4 },
    { key: 'pp_hayes_fisher', client: 'sterling', relationship: 'owns', occupancy: 'second_home', nickname: 'Palmyra 4421', deal: 'hayes2023', role: 'bought', street: '12 Palmyra Court', unit: '4421', buildingName: 'The Palmyra at Fisher Island', neighborhood: 'Fisher Island', propertyType: 'condo', style: 'Mediterranean Revival', family: 'Mediterranean', beds: 4, baths: 5, sqft: 4600, yearBuilt: 2008, waterfront: 'oceanfront', views: ['ocean'], estValue: 11900000, valueSource: 'cma', titleHolding: 'trust', loanType: 'cash', hoaMonthly: 10200, photos: 4 },
    { key: 'pp_hayes_sunny', client: 'sterling', relationship: 'leased_out', occupancy: 'rental', nickname: 'Oceanique 4705 (leased)', street: '300 Oceanique Way', unit: '4705', buildingName: 'Oceanique Sunny Isles', neighborhood: 'Sunny Isles', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 3, baths: 3.5, sqft: 2900, yearBuilt: 2018, waterfront: 'oceanfront', bought: [-250, 7], purchasePrice: 3100000, estValue: 4300000, valueSource: 'avm', titleHolding: 'llc', loanType: 'cash', rentAmount: 16000, leaseEndsAt: ctx.at(150, 12), hoaMonthly: 4800, photos: 3 },

    // Anniversaries + other past-client homes
    { key: 'pp_moreno_boca', client: 'celeste', relationship: 'owns', occupancy: 'primary', deal: 'moreno', role: 'bought', street: '2240 Royal Egret Lane', neighborhood: 'Boca Raton', propertyType: SF, style: 'Mediterranean Revival', family: 'Mediterranean', beds: 5, baths: 4.5, sqft: 4700, lotSqft: 14000, yearBuilt: 2003, waterfront: 'intracoastal', frontage: 90, dock: 60, appreciation: 1.07, lenderName: 'Coastal Federal Jumbo Lending', loanType: 'fixed', mortgageRate: 6.625, ltv: 0.7, photos: 4 },
    { key: 'pp_stein_pinecrest', client: 'joel', relationship: 'owns', occupancy: 'primary', deal: 'stein', role: 'bought', street: '7311 Kendall Oaks Drive', neighborhood: 'Pinecrest', propertyType: SF, style: 'Modern', family: 'Modern', beds: 5, baths: 5.5, sqft: 5600, lotSqft: 38000, yearBuilt: 2019, appreciation: 1.06, lenderName: 'Meridian Coast Private Bank', loanType: 'fixed', mortgageRate: 6.875, ltv: 0.65, photos: 4 },
    { key: 'pp_monroe_grove', client: 'wes', relationship: 'owns', occupancy: 'primary', deal: 'monroe2022', role: 'bought', street: '2985 Coral Shade Lane', neighborhood: 'Coconut Grove', propertyType: SF, style: 'Tropical Modern', family: 'Tropical Modern', beds: 4, baths: 4, sqft: 3600, lotSqft: 9800, yearBuilt: 2014, appreciation: 1.31, lenderName: 'Coastal Federal Jumbo Lending', loanType: 'fixed', mortgageRate: 3.5, ltv: 0.75, photos: 4 },
    { key: 'pp_calloway_brickell', client: 'james', relationship: 'owns', occupancy: 'primary', nickname: 'Brickell Shore 2207', street: '1550 Brickell Shore Drive', unit: '2207', buildingName: 'Brickell Shore Residences', neighborhood: 'Brickell', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 2, baths: 2.5, sqft: 1650, yearBuilt: 2017, views: ['bay'], bought: [52, 7], purchasePrice: 1350000, estValue: 1720000, valueSource: 'avm', titleHolding: 'individual', lenderName: 'Brightwater Private Bank', mortgageBalance: 905000, mortgageRate: 3.375, loanType: 'arm', loanResetAt: ctx.at(52, 12), loanYears: 30, hoaMonthly: 1900,
      thinkingOfSelling: true, sellSignals: [
        { signal: 'arm_reset', strength: 0.75, quote: 'If my rate jumps to seven I’d rather sell and rent for a year.', source: 'text' },
        { signal: 'relocation', strength: 0.5, quote: 'Gym number two is opening in Fort Lauderdale — might move up there.', source: 'call' },
      ], photos: 3 },
    { key: 'pp_novak_a', client: 'stefan', relationship: 'leased_out', occupancy: 'rental', nickname: 'Vela 1905 (leased)', street: '60 Vela Bay Walk', unit: '1905', buildingName: 'Vela Brickell', neighborhood: 'Brickell', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 2, baths: 2, sqft: 1450, yearBuilt: 2019, bought: [98, 3], purchasePrice: 1150000, estValue: 1300000, valueSource: 'avm', titleHolding: 'llc', lenderName: 'Brightwater Private Bank', mortgageBalance: 860000, mortgageRate: 4.25, loanType: 'arm', loanResetAt: ctx.at(98, 12), loanYears: 30, rentAmount: 7900, leaseEndsAt: ctx.at(120, 12), hoaMonthly: 1750, photos: 3, notes: '3/1 interest-only ARM.' },
    { key: 'pp_novak_b', client: 'stefan', relationship: 'leased_out', occupancy: 'rental', nickname: 'Vela 2304 (leased)', street: '60 Vela Bay Walk', unit: '2304', buildingName: 'Vela Brickell', neighborhood: 'Brickell', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 2, baths: 2.5, sqft: 1600, yearBuilt: 2019, bought: [-90, 6], purchasePrice: 990000, estValue: 1420000, valueSource: 'avm', titleHolding: 'llc', mortgageBalance: 610000, mortgageRate: 3.25, loanType: 'fixed', loanYears: 30, rentAmount: 8400, leaseEndsAt: ctx.at(40, 12), hoaMonthly: 1850, photos: 3 },

    // Renters
    { key: 'pp_ferraro_rent', client: 'isabella', relationship: 'rents', occupancy: 'primary', nickname: 'Vela 3204 (renting)', street: '60 Vela Bay Walk', unit: '3204', buildingName: 'Vela Brickell', neighborhood: 'Brickell', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 2, baths: 2.5, sqft: 1750, yearBuilt: 2019, views: ['bay', 'skyline'], rentAmount: 14500, leaseEndsAt: ctx.at(38, 12), photos: 3 },
    { key: 'pp_bellini_rent', client: 'marco', relationship: 'rents', occupancy: 'primary', nickname: 'South of Fifth rental', street: '5 Pointe Azure Way', unit: '1204', buildingName: 'Pointe Azure South Beach', neighborhood: 'Miami Beach', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 3, baths: 3, sqft: 2100, yearBuilt: 2016, views: ['ocean'], rentAmount: 18000, leaseEndsAt: ctx.at(64, 12), photos: 3, notes: 'Landlord asking +9% on renewal.' },
    { key: 'pp_park_rent', client: 'chloe', relationship: 'rents', occupancy: 'primary', nickname: 'Grove townhouse (renting)', street: '3180 Grove Isle Mews', neighborhood: 'Coconut Grove', propertyType: 'townhouse', style: 'Tropical Modern', family: 'Tropical Modern', beds: 3, baths: 3.5, sqft: 2400, yearBuilt: 2018, rentAmount: 11000, leaseEndsAt: ctx.at(82, 12), photos: 3 },

    // Sold history (listing side)
    { key: 'pp_kessler_solace', client: 'adrian', relationship: 'sold', occupancy: 'second_home', deal: 'kessler', role: 'sold', listing: 'own_solace', street: '88 Surfside Strand', unit: '803', buildingName: 'Solace Surfside', neighborhood: 'Surfside', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 3, baths: 3.5, sqft: 2650, yearBuilt: 2017, waterfront: 'oceanfront', bought: [-160, 9], purchasePrice: 2900000, photos: 3 },
    { key: 'pp_feld_pinecrest', client: 'jonah', relationship: 'sold', occupancy: 'primary', deal: 'feld', role: 'sold', listing: 'own_oldcutler', street: '6940 Old Cutler Bend', neighborhood: 'Pinecrest', propertyType: SF, style: 'British Colonial', family: 'Colonial', beds: 6, baths: 6.5, sqft: 6800, lotAcres: 1.2, yearBuilt: 2008, bought: [-120, 15], purchasePrice: 2800000, photos: 3 },
    { key: 'pp_marlow_aurelia', client: 'olivia', relationship: 'sold', occupancy: 'primary', deal: 'marlow', role: 'sold', listing: 'own_aurelia', street: '1201 Aurelia Bay Drive', unit: 'PH5', buildingName: 'Aurelia Brickell', neighborhood: 'Brickell', propertyType: 'penthouse', style: 'Contemporary', family: 'Contemporary', beds: 4, baths: 4.5, sqft: 4300, yearBuilt: 2019, bought: [-300, 6], purchasePrice: 3000000, photos: 3 },
    { key: 'pp_thornton_ge', client: 'william', relationship: 'sold', occupancy: 'primary', deal: 'thornton', role: 'sold', street: '3 Heron Point Road', neighborhood: 'Gables Estates', propertyType: 'estate', style: 'Contemporary', family: 'Contemporary', beds: 7, baths: 8, sqft: 9800, lotAcres: 1.1, yearBuilt: 2001, waterfront: 'bayfront', frontage: 180, dock: 95, bought: [-40, 28], purchasePrice: 3400000, photos: 3 },
    { key: 'pp_hale_pb', client: 'preston', relationship: 'sold', occupancy: 'second_home', deal: 'hale', role: 'sold', street: '118 Coral Vine Way', neighborhood: 'Palm Beach', propertyType: SF, style: 'British Colonial', family: 'Colonial', beds: 5, baths: 5.5, sqft: 5900, lotSqft: 16500, yearBuilt: 1962, yearRenovated: 2012, bought: [-70, 12], purchasePrice: 5100000, photos: 3 },
    { key: 'pp_ashby_gables', client: 'frederick', relationship: 'sold', occupancy: 'primary', deal: 'ashby', role: 'sold', street: '925 Sevilla Arch Avenue', neighborhood: 'Coral Gables', propertyType: SF, style: 'Mediterranean Revival', family: 'Mediterranean', beds: 4, baths: 3.5, sqft: 3800, lotSqft: 12000, yearBuilt: 1925, bought: [-260, 32], purchasePrice: 850000, photos: 3 },

    // Bought with me this year
    { key: 'pp_duarte_gables', client: 'sebastian', relationship: 'owns', occupancy: 'primary', deal: 'duarte', role: 'bought', street: '1215 Alhambra Vista Court', neighborhood: 'Coral Gables', propertyType: SF, style: 'Mediterranean Revival', family: 'Mediterranean', beds: 5, baths: 4.5, sqft: 4900, lotSqft: 13500, yearBuilt: 1928, yearRenovated: 2018, appreciation: 1, lenderName: 'Meridian Coast Private Bank', loanType: 'fixed', mortgageRate: 6.375, ltv: 0.7, photos: 4 },
    { key: 'pp_vance_aria', client: 'meredith', relationship: 'owns', occupancy: 'primary', deal: 'vance', role: 'bought', street: '10 Harbour Crest Way', unit: '905', buildingName: 'The Aria at Bal Harbour', neighborhood: 'Bal Harbour', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 3, baths: 3.5, sqft: 3000, yearBuilt: 2016, waterfront: 'oceanfront', views: ['ocean'], appreciation: 1, loanType: 'cash', hoaMonthly: 6300, photos: 4 },
    { key: 'pp_larsen_kb', client: 'henrik', relationship: 'owns', occupancy: 'primary', deal: 'larsen', role: 'bought', street: '18 Mashta Cove Lane', neighborhood: 'Key Biscayne', propertyType: SF, style: 'Modern', family: 'Modern', beds: 4, baths: 4.5, sqft: 3900, lotSqft: 11000, yearBuilt: 2012, waterfront: 'canal', frontage: 75, dock: 50, appreciation: 1.04, loanType: 'cash', photos: 4 },
    { key: 'pp_grant_grove', client: 'theo', relationship: 'owns', occupancy: 'primary', deal: 'grant', role: 'bought', street: '3611 Avocado Grove Lane', neighborhood: 'Coconut Grove', propertyType: SF, style: 'Tropical Modern', family: 'Tropical Modern', beds: 4, baths: 4, sqft: 3400, lotSqft: 10000, yearBuilt: 2015, appreciation: 1.03, lenderName: 'Coastal Federal Jumbo Lending', loanType: 'fixed', mortgageRate: 6.5, ltv: 0.75, photos: 4 },
    { key: 'pp_reyes_edgewater', client: 'amara', relationship: 'owns', occupancy: 'primary', deal: 'reyes', role: 'bought', street: '520 Bayside Lofts Way', unit: '1204', buildingName: 'Bayside Lofts Edgewater', neighborhood: 'Edgewater', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 3, baths: 3, sqft: 2200, yearBuilt: 2020, views: ['bay'], appreciation: 1.02, lenderName: 'Meridian Coast Private Bank', loanType: 'fixed', mortgageRate: 6.25, ltv: 0.6, hoaMonthly: 2600, photos: 3 },
    { key: 'pp_whitmore_lasolas', client: 'grace', relationship: 'owns', occupancy: 'primary', deal: 'whitmore', role: 'bought', street: '612 Royal Plaza Isle', neighborhood: 'Las Olas', propertyType: SF, style: 'Modern', family: 'Modern', beds: 4, baths: 4.5, sqft: 4100, lotSqft: 10500, yearBuilt: 2017, waterfront: 'canal', frontage: 80, dock: 60, appreciation: 1.01, lenderName: 'Coastal Federal Jumbo Lending', loanType: 'fixed', mortgageRate: 6.5, ltv: 0.7, photos: 4 },
    { key: 'pp_watanabe_vela', client: 'kenji', relationship: 'owns', occupancy: 'primary', deal: 'watanabe', role: 'bought', street: '60 Vela Bay Walk', unit: '3306', buildingName: 'Vela Brickell', neighborhood: 'Brickell', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 3, baths: 3, sqft: 2150, yearBuilt: 2019, views: ['bay', 'skyline'], appreciation: 1, lenderName: 'Meridian Coast Private Bank', loanType: 'fixed', mortgageRate: 6.125, ltv: 0.8, hoaMonthly: 2700, photos: 3 },
    { key: 'pp_volkov_sunny', client: 'dmitri', relationship: 'owns', occupancy: 'investment', nickname: 'Oceanique 2108 (seasonal rental)', deal: 'volkov', role: 'bought', street: '300 Oceanique Way', unit: '2108', buildingName: 'Oceanique Sunny Isles', neighborhood: 'Sunny Isles', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 2, baths: 2.5, sqft: 1700, yearBuilt: 2018, waterfront: 'oceanfront', appreciation: 1.05, loanType: 'cash', rentAmount: 9000, hoaMonthly: 2900, photos: 3 },

    // Sellers + others
    { key: 'pp_laurent_lagorce', client: 'simone', relationship: 'owns', occupancy: 'primary', listing: 'own_lagorce', street: '2741 Fairway Isle Drive', neighborhood: 'La Gorce', propertyType: SF, style: 'Mediterranean Revival', family: 'Mediterranean', beds: 6, baths: 6.5, sqft: 7200, lotSqft: 22500, yearBuilt: 1928, waterfront: 'canal', frontage: 120, dock: 60, bought: [-75, 13], purchasePrice: 4600000, estValue: 12900000, valueSource: 'listing', titleHolding: 'llc', loanType: 'cash', photos: 4 },
    { key: 'pp_alvarez_grove', client: 'beatriz', relationship: 'owns', occupancy: 'primary', listing: 'own_mangrove', street: '3417 Mangrove Point Road', neighborhood: 'Coconut Grove', propertyType: SF, style: 'Tropical Modern', family: 'Tropical Modern', beds: 5, baths: 5.5, sqft: 5600, lotSqft: 15200, yearBuilt: 2016, bought: [-190, 13], purchasePrice: 1400000, estValue: 7400000, valueSource: 'listing', titleHolding: 'joint', lenderName: 'Brightwater Private Bank', mortgageBalance: 1850000, mortgageRate: 3.75, loanType: 'fixed', loanYears: 30, photos: 4, notes: 'Bought the lot in 2013 and built; under contract at $7.4M.' },
    { key: 'pp_fontaine_aria', client: 'lydia', relationship: 'owns', occupancy: 'second_home', nickname: 'Mom’s Aria residence', listing: 'own_aria1402', street: '10 Harbour Crest Way', unit: '1402', buildingName: 'The Aria at Bal Harbour', neighborhood: 'Bal Harbour', propertyType: 'condo', style: 'Contemporary', family: 'Contemporary', beds: 3, baths: 3.5, sqft: 3100, yearBuilt: 2016, waterfront: 'oceanfront', estValue: 6450000, valueSource: 'listing', titleHolding: 'trust', loanType: 'cash', hoaMonthly: 6450, photos: 3, notes: 'Inherited; held in her late mother’s trust.' },
    { key: 'pp_raman_sf', client: 'priya', relationship: 'owns', occupancy: 'primary', nickname: 'Pacific Heights house', city: 'San Francisco', state: 'CA', zip: '94123', market: 'San Francisco', propertyType: SF, style: 'Edwardian', family: 'Classical', beds: 4, baths: 3.5, sqft: 3300, yearBuilt: 1908, bought: [-20, 6], purchasePrice: 3900000, estValue: 4600000, valueSource: 'manual', titleHolding: 'joint', mortgageBalance: 2300000, mortgageRate: 2.75, loanType: 'fixed', loanYears: 30, thinkingOfSelling: false, photos: 3, notes: 'Listing in SF after the kids finish the semester; proceeds go to the Miami down payment.' },
    { key: 'pp_karimova_london', client: 'nadia', relationship: 'owns', occupancy: 'primary', nickname: 'Mayfair flat', city: 'London', state: null, market: 'London', propertyType: 'condo', style: 'Georgian', family: 'Classical', beds: 3, baths: 3, sqft: 2600, yearBuilt: 1790, bought: [-300, 4], purchasePrice: 9500000, estValue: 9800000, valueSource: 'manual', titleHolding: 'llc', loanType: 'cash', photos: 3 },
    { key: 'pp_mercer_grove', client: 'diane', relationship: 'leased_out', occupancy: 'rental', nickname: 'Grove Isle Mews townhouse', street: '3044 Grove Isle Mews', neighborhood: 'Coconut Grove', propertyType: 'townhouse', style: 'Tropical Modern', family: 'Tropical Modern', beds: 3, baths: 3.5, sqft: 2300, yearBuilt: 2018, bought: [-40, 6], purchasePrice: 1250000, estValue: 1750000, valueSource: 'avm', titleHolding: 'individual', loanType: 'cash', rentAmount: 9800, leaseEndsAt: ctx.at(190, 12), photos: 3 },
    { key: 'pp_adeyemi_weston', client: 'malik', relationship: 'owns', occupancy: 'primary', nickname: 'Weston house', street: '2780 Heron Lake Drive', city: 'Weston', state: 'FL', zip: '33327', market: 'Broward', propertyType: SF, style: 'Mediterranean Revival', family: 'Mediterranean', beds: 5, baths: 4.5, sqft: 4800, lotSqft: 21000, yearBuilt: 2006, waterfront: 'lake', bought: [-210, 9], purchasePrice: 1350000, estValue: 2400000, valueSource: 'avm', titleHolding: 'joint', mortgageBalance: 1100000, mortgageRate: 3.25, loanType: 'fixed', loanYears: 30,
      sellSignals: [{ signal: 'move_up', strength: 0.4, quote: 'We sell Weston the day after we find the right dock.', source: 'text' }], photos: 3 },
    { key: 'pp_sinclair_watch', client: 'ava', relationship: 'watching', nickname: 'Phase II PH — waiting on pricing', listing: 'wh_cpphase2', source: 'described' },
    { key: 'pp_moreau_montreal', client: 'lucas', relationship: 'owns', occupancy: 'primary', nickname: 'Westmount house', city: 'Montréal', state: 'QC', market: 'Montréal', propertyType: SF, style: 'Victorian', family: 'Classical', beds: 5, baths: 4, sqft: 4800, yearBuilt: 1899, bought: [-80, 12], purchasePrice: 2100000, estValue: 3900000, valueSource: 'manual', titleHolding: 'joint', loanType: 'cash', photos: 3 },
  ];

  // ── Buyer searches ──────────────────────────────────────────────────────
  const mh = (feature, importance, source, extra = {}) => ({ feature, importance, source, ...extra });
  const searches = [
    { key: 's_delacroix', client: 'julien', name: 'Bayfront estate · Venetian Islands', bucket: 'active', status: 'found', markets: ['Miami Beach'], neighborhoods: ['Venetian Islands', 'Sunset Islands', 'La Gorce'], propertyTypes: ['single_family', 'estate'], priceMin: 10000000, priceMax: 16000000, bedsMin: 5, bathsMin: 5, sqftMin: 6000, lotSqftMin: 12000, styles: ['Tropical Modern', 'Modern', 'Contemporary'], waterfront: ['bayfront'], views: ['bay', 'skyline'],
      mustHaves: [mh('dock', 1, 'call', { min: 90 }), mh('no_fixed_bridges', 1, 'call'), mh('wine_room', 0.8, 'text'), mh('home_office', 0.7, 'call'), mh('pool', 0.8, 'search'), mh('gated', 0.5, 'search')],
      niceToHaves: ['rooftop terrace', 'elevator'], dealBreakers: ['Dock under 85 ft', 'Fixed bridge to the bay'], timeline: 'asap', financing: 'preapproved', notes: 'Found — under contract on 41 Isola Verde Drive.', created: -72 },
    { key: 's_delacroix_dream', client: 'julien', name: 'Someday · Star Island', bucket: 'dream', markets: ['Miami Beach'], neighborhoods: ['Star Island'], propertyTypes: ['estate'], priceMin: 35000000, priceMax: 50000000, bedsMin: 7, waterfront: ['bayfront'], mustHaves: [mh('dock', 1, 'call', { min: 140 }), mh('guard_gated', 0.8, 'call')], timeline: 'someday', notes: '“When the company sells.” — Julien', created: -40 },
    { key: 's_ashcombe', client: 'victoria', name: 'Oceanfront estate · Golden Beach', bucket: 'active', markets: ['Golden Beach', 'Miami Beach'], neighborhoods: ['Golden Beach', 'Indian Creek', 'Bal Harbour'], propertyTypes: ['estate', 'single_family'], priceMin: 25000000, priceMax: 45000000, budgetFlexible: true, bedsMin: 6, bathsMin: 7, sqftMin: 9000, lotSqftMin: 22000, styles: ['Contemporary', 'Modern'], waterfront: ['oceanfront'], views: ['ocean'],
      mustHaves: [mh('private_beach', 1, 'call'), mh('gated', 0.9, 'call'), mh('staff_quarters', 0.9, 'call'), mh('ceiling_height', 0.8, 'note', { min: 12 }), mh('gym', 0.6, 'search'), mh('spa', 0.5, 'search'), mh('wine_room', 0.4, 'text')],
      niceToHaves: ['20-ft gallery wall', 'dock'], dealBreakers: ['Busy road frontage', 'Overlooked by neighbors', 'Ceilings under 11 ft'], timeline: '90d', financing: 'cash_pof', created: -40 },
    { key: 's_ashcombe_dream', client: 'victoria', name: 'Indian Creek waterfront compound', bucket: 'dream', markets: ['Indian Creek'], neighborhoods: ['Indian Creek'], propertyTypes: ['estate'], priceMin: 50000000, priceMax: 65000000, bedsMin: 8, waterfront: ['bayfront', 'oceanfront'], mustHaves: [mh('guard_gated', 1, 'call'), mh('guest_house', 0.8, 'call'), mh('dock', 0.6, 'call', { min: 100 })], timeline: '12mo', financing: 'cash_pof', created: -30 },
    { key: 's_raman', client: 'priya', name: 'Family home near top schools · Grove / Gables', bucket: 'active', markets: ['Miami', 'Coral Gables'], neighborhoods: ['Coconut Grove', 'Coral Gables'], propertyTypes: ['single_family'], priceMin: 4000000, priceMax: 7500000, bedsMin: 4, bathsMin: 4, sqftMin: 4000, lotSqftMin: 9000, yearBuiltMin: 1920, styles: ['Tropical Modern', 'Mediterranean Revival', 'Modern'],
      mustHaves: [mh('home_office', 1, 'call', { min: 2 }), mh('pool', 0.8, 'search'), mh('pool_fence', 0.7, 'call'), mh('walkable', 0.7, 'call'), mh('school_zone', 1, 'call')],
      niceToHaves: ['guest suite', 'garage gym'], dealBreakers: ['Busy street', 'Over 20 minutes to Biscayne Prep'], timeline: '90d', financing: 'preapproved', created: -18 },
    { key: 's_raman_dream', client: 'priya', name: 'Weekend place · Key Biscayne', bucket: 'dream', markets: ['Key Biscayne'], neighborhoods: ['Key Biscayne'], propertyTypes: ['single_family', 'condo'], priceMin: 3000000, priceMax: 5000000, waterfront: ['bayfront', 'oceanfront'], timeline: 'someday', notes: 'Dev wants to learn to sail.', created: -8 },
    { key: 's_cole', client: 'ethan', name: 'Pinecrest family estate · 1 acre', bucket: 'active', status: 'found', markets: ['Pinecrest'], neighborhoods: ['Pinecrest'], propertyTypes: ['single_family'], priceMin: 5000000, priceMax: 7000000, bedsMin: 5, bathsMin: 5, sqftMin: 5500, lotSqftMin: 40000, styles: ['Modern', 'Contemporary'], mustHaves: [mh('pool', 1, 'search'), mh('pool_fence', 0.9, 'text'), mh('generator', 0.7, 'call'), mh('summer_kitchen', 0.6, 'text')], dealBreakers: ['Shared driveway'], timeline: 'asap', financing: 'preapproved', notes: 'Found — 8120 Banyan Ridge Lane.', created: -45 },
    { key: 's_karimova', client: 'nadia', name: 'Fisher Island residence', bucket: 'active', markets: ['Fisher Island'], neighborhoods: ['Fisher Island'], propertyTypes: ['condo', 'villa', 'penthouse'], priceMin: 8000000, priceMax: 15000000, bedsMin: 4, bathsMin: 4, sqftMin: 4000, waterfront: ['oceanfront'], views: ['ocean'], mustHaves: [mh('tennis', 0.9, 'call'), mh('private_beach', 0.8, 'search'), mh('staff_quarters', 0.5, 'call'), mh('turnkey', 0.8, 'call')], timeline: '90d', financing: 'cash_pof', created: -26 },
    { key: 's_okafor', client: 'daniel', name: 'Edgewater penthouse with room for a piano', bucket: 'active', status: 'found', markets: ['Miami'], neighborhoods: ['Edgewater', 'Brickell'], propertyTypes: ['penthouse', 'condo'], priceMin: 6000000, priceMax: 10000000, bedsMin: 3, sqftMin: 4000, views: ['bay'], mustHaves: [mh('ceiling_height', 0.8, 'call', { min: 11 }), mh('music_room', 0.7, 'call'), mh('rooftop_terrace', 0.6, 'search')], timeline: 'asap', financing: 'preapproved', notes: 'Found — One Harbor Point PH 4501.', created: -56 },
    { key: 's_okafor_dream', client: 'daniel', name: 'Coconut Grove bayfront someday', bucket: 'dream', markets: ['Miami'], neighborhoods: ['Coconut Grove'], propertyTypes: ['single_family'], priceMin: 9000000, priceMax: 14000000, waterfront: ['bayfront'], timeline: 'someday', created: -30 },
    { key: 's_moreau', client: 'lucas', name: 'Bal Harbour oceanfront, turnkey', bucket: 'active', status: 'found', markets: ['Bal Harbour', 'Surfside'], neighborhoods: ['Bal Harbour', 'Surfside'], buildings: ['The Aria at Bal Harbour', 'Seaview Bal Harbour'], propertyTypes: ['condo'], priceMin: 4000000, priceMax: 6500000, bedsMin: 3, waterfront: ['oceanfront'], mustHaves: [mh('turnkey', 0.9, 'call'), mh('private_beach', 0.8, 'search')], timeline: 'asap', financing: 'cash_pof', notes: 'Found — The Aria 1102.', created: -46 },
    { key: 's_ferraro', client: 'isabella', name: 'First purchase · Edgewater / Design District', bucket: 'active', markets: ['Miami'], neighborhoods: ['Edgewater', 'Brickell'], propertyTypes: ['condo'], priceMin: 2000000, priceMax: 3200000, bedsMin: 2, sqftMin: 1700, views: ['bay'], mustHaves: [mh('gallery_wall', 0.9, 'text', { min: 20 }), mh('pet_friendly', 0.8, 'text'), mh('ceiling_height', 0.6, 'call', { min: 10 })], dealBreakers: ['No dogs over 20 lbs'], timeline: '90d', financing: 'prequalified', created: -16 },
    { key: 's_sinclair', client: 'ava', name: 'Casa Palmera Phase II · PH or 26+ floor', bucket: 'active', markets: ['Miami'], neighborhoods: ['Coconut Grove'], buildings: ['Casa Palmera Residences'], propertyTypes: ['penthouse', 'condo'], priceMin: 6000000, priceMax: 13000000, bedsMin: 4, views: ['bay'], mustHaves: [mh('rooftop_terrace', 0.9, 'call'), mh('high_floor', 0.9, 'call', { min: 26 })], timeline: '12mo', financing: 'cash_pof', created: -60 },
    { key: 's_ricci', client: 'leo', name: 'Rental condos · Brickell / Edgewater · 4.5% cap', bucket: 'active', markets: ['Miami', 'Bay Harbor Islands'], neighborhoods: ['Brickell', 'Edgewater', 'Bay Harbor Islands'], propertyTypes: ['condo'], priceMin: 1500000, priceMax: 3500000, bedsMin: 2, mustHaves: [mh('rental_policy_30_day', 1, 'call'), mh('cap_rate', 0.9, 'call', { min: 4.5 })], timeline: '6mo', financing: 'preapproved', created: -22 },
    { key: 's_langford', client: 'tessa', name: 'Miami Beach modern · walk to the beach', bucket: 'active', markets: ['Miami Beach'], neighborhoods: ['Miami Beach', 'La Gorce', 'Sunset Islands'], propertyTypes: ['single_family', 'townhouse'], priceMin: 3000000, priceMax: 4500000, bedsMin: 3, styles: ['Modern', 'Tropical Modern'], mustHaves: [mh('pool', 0.8, 'search'), mh('yard_for_dog', 0.8, 'text'), mh('walk_to_beach', 0.7, 'call')], timeline: '90d', financing: 'preapproved', created: -20 },
    { key: 's_henderson', client: 'jamal', name: 'Pinecrest pool home · 1 acre', bucket: 'active', markets: ['Pinecrest'], neighborhoods: ['Pinecrest'], propertyTypes: ['single_family'], priceMin: 3000000, priceMax: 5000000, bedsMin: 4, lotSqftMin: 30000, mustHaves: [mh('pool', 1, 'search'), mh('pool_fence', 0.7, 'call')], timeline: '6mo', financing: 'prequalified', created: -25 },
    { key: 's_petrova', client: 'elena', name: 'Sunny Isles oceanfront · high floor', bucket: 'active', markets: ['Sunny Isles Beach', 'Bal Harbour'], neighborhoods: ['Sunny Isles', 'Bal Harbour'], propertyTypes: ['condo', 'penthouse'], priceMin: 4000000, priceMax: 6000000, bedsMin: 3, waterfront: ['oceanfront'], views: ['ocean'], mustHaves: [mh('high_floor', 0.9, 'call', { min: 30 }), mh('private_beach', 0.6, 'search'), mh('studio_space', 0.5, 'text')], timeline: '90d', financing: 'cash_pof', created: -38 },
    { key: 's_rossi', client: 'bianca', name: 'Surfside oceanfront · terrace', bucket: 'active', markets: ['Surfside', 'Bal Harbour'], neighborhoods: ['Surfside', 'Bal Harbour'], propertyTypes: ['penthouse', 'condo'], priceMin: 5000000, priceMax: 7500000, bedsMin: 3, waterfront: ['oceanfront'], mustHaves: [mh('rooftop_terrace', 0.9, 'search'), mh('terrace_sqft', 0.8, 'text', { min: 1000 })], timeline: '30d', financing: 'cash_pof', created: -43 },
    { key: 's_brandt', client: 'noah', name: 'Coral Gables Mediterranean · under $5M', bucket: 'active', markets: ['Coral Gables'], neighborhoods: ['Coral Gables'], propertyTypes: ['single_family'], priceMin: 3500000, priceMax: 5000000, bedsMin: 4, styles: ['Mediterranean Revival', 'Spanish Revival'], mustHaves: [mh('home_office', 0.8, 'search'), mh('pool', 0.6, 'search')], timeline: '6mo', created: -6 },
    { key: 's_feld', client: 'jonah', name: 'Jupiter Island retreat', bucket: 'active', markets: ['Jupiter Island'], neighborhoods: ['Jupiter Island'], propertyTypes: ['single_family'], priceMin: 6000000, priceMax: 9000000, bedsMin: 4, lotSqftMin: 40000, waterfront: ['intracoastal', 'oceanfront'], mustHaves: [mh('near_golf', 0.9, 'call'), mh('dock', 0.4, 'call')], timeline: '6mo', financing: 'cash_pof', created: -30 },
    { key: 's_adeyemi', client: 'malik', name: 'Las Olas deep-water · sportfish dock', bucket: 'active', markets: ['Fort Lauderdale'], neighborhoods: ['Las Olas'], propertyTypes: ['single_family'], priceMin: 4000000, priceMax: 7000000, bedsMin: 4, waterfront: ['canal', 'intracoastal'], mustHaves: [mh('dock', 1, 'call', { min: 80 }), mh('no_fixed_bridges', 1, 'call'), mh('water_depth_low_tide', 0.9, 'text', { min: 8 }), mh('boat_lift', 0.5, 'search')], dealBreakers: ['Fixed bridges between the house and the inlet'], timeline: '6mo', financing: 'preapproved', created: -55 },
    { key: 's_hartmann', client: 'victor', name: 'Golden Beach oceanfront lot to build', bucket: 'active', markets: ['Golden Beach'], neighborhoods: ['Golden Beach'], propertyTypes: ['land', 'single_family'], priceMin: 15000000, priceMax: 25000000, lotSqftMin: 20000, waterfront: ['oceanfront'], mustHaves: [mh('teardown_ok', 0.9, 'call'), mh('frontage_ft', 0.8, 'call', { min: 75 })], timeline: '12mo', financing: 'cash_pof', created: -200 },
    { key: 's_whitaker', client: 'graham', name: 'In-town Palm Beach · walk to Worth Ave', bucket: 'active', markets: ['Palm Beach'], neighborhoods: ['Palm Beach'], propertyTypes: ['single_family'], priceMin: 9000000, priceMax: 14000000, bedsMin: 4, styles: ['British Colonial', 'Mediterranean Revival'], mustHaves: [mh('walkable', 0.9, 'call'), mh('guest_house', 0.6, 'call'), mh('low_maintenance', 0.8, 'call')], timeline: '90d', financing: 'cash_pof', notes: 'Buy after 128 Sunset Drive closes.', created: -40 },
    { key: 's_brennan', client: 'harold', name: 'Bal Harbour oceanfront condo · one level', bucket: 'active', markets: ['Bal Harbour', 'Surfside'], neighborhoods: ['Bal Harbour', 'Surfside'], buildings: ['The Aria at Bal Harbour', 'Seaview Bal Harbour'], propertyTypes: ['condo'], priceMin: 4000000, priceMax: 7000000, bedsMin: 3, waterfront: ['oceanfront'], views: ['ocean'], mustHaves: [mh('single_level', 1, 'call'), mh('elevator', 1, 'note'), mh('pet_friendly', 0.5, 'call')], timeline: '6mo', financing: 'contingent', created: -14 },
    // Dream / inferred
    { key: 's_montoya_dream', client: 'rafael', name: 'Penthouse with rooftop pool · Brickell', bucket: 'dream', markets: ['Miami'], neighborhoods: ['Brickell', 'Edgewater'], propertyTypes: ['penthouse'], priceMin: 12000000, priceMax: 20000000, mustHaves: [mh('rooftop_pool', 1, 'call')], timeline: 'someday', created: -100 },
    { key: 's_hayes_dream', client: 'sterling', name: 'Golden Beach lot to build', bucket: 'dream', markets: ['Golden Beach'], neighborhoods: ['Golden Beach'], propertyTypes: ['land'], priceMin: 18000000, priceMax: 30000000, waterfront: ['oceanfront'], timeline: 'someday', created: -300 },
    { key: 's_watanabe_dream', client: 'kenji', name: 'Sunset Islands modern · in 3–4 years', bucket: 'dream', markets: ['Miami Beach'], neighborhoods: ['Sunset Islands'], propertyTypes: ['single_family'], priceMin: 9000000, priceMax: 16000000, waterfront: ['bayfront'], styles: ['Modern'], timeline: 'someday', created: -20 },
    { key: 's_vance_dream', client: 'meredith', name: 'Palm Beach winter cottage', bucket: 'dream', markets: ['Palm Beach'], neighborhoods: ['Palm Beach'], propertyTypes: ['single_family'], priceMin: 5000000, priceMax: 9000000, timeline: 'someday', created: -15 },
    { key: 's_bellini_inferred', client: 'marco', name: 'Buy instead of renew? · South Beach', bucket: 'inferred', markets: ['Miami Beach'], neighborhoods: ['Miami Beach'], propertyTypes: ['condo'], priceMin: 1800000, priceMax: 3000000, bedsMin: 2, waterfront: ['oceanfront'], timeline: '90d', notes: 'Inferred from lease ending {date:+64} and the 9% renewal ask.', created: -3 },
    { key: 's_park_inferred', client: 'chloe', name: 'Grove townhouse to own', bucket: 'inferred', markets: ['Miami'], neighborhoods: ['Coconut Grove'], propertyTypes: ['townhouse', 'single_family'], priceMin: 1800000, priceMax: 2800000, bedsMin: 3, timeline: '12mo', notes: 'Inferred: asked twice what the townhouse she rents would sell for.', created: -4 },
  ];

  return { props, searches };
};
