// Hero conversation scripts. Message tuple: [day, 'HH:MM', who, text, extra]
//   day  : offset from today (0 = today, -1 = yesterday) or 'close:<dealKey>[±n]'
//   who  : 'me' | 'c' (the thread's client) | a client key (group chats) | 'x' (unknown sender)
//   extra: { listing, att: ['listing:<key>:n' | 'int:i' | 'ext:i'], react: [{type, fromMe}],
//            status, error, campaign: 'justlisted'|'openhouse', ask: '<key>' (Serena captures) }
module.exports = function heroThreads() {
  return [
    {
      key: 'c_delacroix', client: 'julien', isGroup: true, groupName: 'Isola Verde 🌊', participants: ['julien', 'camille'], handle: 'chat884213907765123401', pinned: true, unread: 1,
      aiSummary: 'Delacroix group thread: under contract on 41 Isola Verde at $14.9M with a $35K seawall credit; inspection cleared, appraisal visit done and report pending. Camille asked this morning whether the appraiser has reported.',
      msgs: [
        [-33, '09:40', 'me', 'Morning, both. Quick recap from yesterday so it lives in one place: 1904 Sunset Isle Way has the light but only 80 ft of dock. 41 Isola Verde has 92 ft and no fixed bridges to the bay. I’ve asked Nicole for the seawall permit history on Isola Verde.'],
        [-33, '09:52', 'julien', 'Ninety-two is the number. Belle Rive is 82 plus the swim platform. Sunset Isle is out.'],
        [-33, '10:05', 'camille', 'I loved the light at Sunset Isle but fine 😄 The kitchen at Isola Verde is very dark though, no?'],
        [-33, '10:11', 'me', 'It is — walnut cabinetry and north-facing windows on that side. Lena, my stager, thinks paint and lighting alone would change it completely. I’ll get you a rough number.'],
        [-31, '18:20', 'me', 'Here’s the Venetian Islands one again with the floor plan — the office Julien wanted is the room off the foyer.', { listing: 'mls_isola' }],
        [-31, '18:44', 'camille', 'Léa has already picked her room 🙄'],
        [-31, '18:46', 'julien', 'Can we see it again Saturday with my captain? He wants to check the approach and the lift.'],
        [-31, '18:50', 'me', 'Done — 9:30, before the wind picks up. I’ll tell Nicole a captain is coming so the lift is powered and ready.'],
        [-26, '21:15', 'julien', 'We talked. We want to offer. 14.6, close in 45 days, 10% deposit.'],
        [-26, '21:22', 'me', 'Good. I’d go 14.6 with a 10-day inspection and an appraisal contingency — the seller has already bought in Aspen and wants certainty more than a top number. I’ll draft tonight and send it for signature by 9.'],
        [-25, '08:58', 'me', 'Offer is in your inboxes. Once signed I’ll send it to Nicole with Marcus’s pre-approval letter and proof of the deposit.'],
        [-25, '09:40', 'camille', 'Signed ✍️'],
        [-25, '09:41', 'julien', 'Signed.'],
        [-24, '17:30', 'me', 'Counter came back at 15.1. Nicole hinted that 14.9 gets it done if we keep the 10-day inspection.'],
        [-24, '17:48', 'julien', '14.9 and they leave the lift remotes and the dock cleats. And the dining table — Camille loves it.'],
        [-24, '17:49', 'camille', 'I do love the table 🙈'],
        [-21, '11:05', 'me', 'Accepted at 14.9 — with the table, the lift remotes and the dock hardware. The executed contract is in your email. Deposit wiring instructions will come from Bayline Title: only trust instructions you have confirmed by calling Rachel Ostrowski at the number I’m sending separately. Never from an email alone.', { react: [{ type: 'love', fromMe: false, by: 'camille' }] }],
        [-21, '11:20', 'julien', 'Merci Alex. Champagne tonight.'],
        [-21, '11:24', 'camille', '🥂🥂🥂'],
        [-17, '14:30', 'me', 'Hank finished the inspection. Big picture: the house is in great shape. Two real items — hairline cracks in the seawall cap along about 30 ft, and the original dock-lift motor. Full report is in your email.', { att: ['listing:mls_isola:2'] }],
        [-17, '14:52', 'julien', 'What does the seawall mean in money?'],
        [-17, '15:03', 'me', 'Hank’s ballpark is $28–40K to repair the cap properly. I’d ask for a $35K credit rather than a repair — you control the contractor and the timing.'],
        [-17, '15:10', 'camille', 'Is it safe for the kids to swim off the dock?'],
        [-17, '15:16', 'me', 'Yes. It’s cosmetic today, not structural — the kind of thing that becomes structural in five to eight years if nobody touches it.'],
        [-14, '10:20', 'me', 'Seller agreed to the $35K credit. Inspection contingency is cleared ✅ Next up: appraisal, then financing.', { react: [{ type: 'like', fromMe: false, by: 'julien' }] }],
        [-14, '10:26', 'julien', 'Excellent.'],
        [-6, '16:05', 'camille', 'Random question — does the Venetian Causeway close often? Drop-off at Biscayne Prep is 7:40 😬'],
        [-6, '16:14', 'me', 'Only for bridge openings and the occasional race or event, and the tender rarely opens during the morning rush. I’ll send you two backup routes over the MacArthur just in case.'],
        [-3, '09:10', 'me', 'Appraiser is booked for {dow:-2} at 10. I’ll meet him there with a comp package — two Venetian sales and the 128 Sunset Drive listing, to show what bayfront with a real dock commands.'],
        [-2, '13:40', 'me', 'Appraisal visit done. He spent most of his time on the dock and the seawall; I walked him through the credit and the permit history. Reports usually take three to five business days.'],
        [-2, '13:55', 'julien', 'If it comes in low, what happens?'],
        [-2, '14:06', 'me', 'Then we have options: the seller reduces, you bring more cash, or we challenge it with better comps. Marcus says the bank has room at 60% loan-to-value. Let’s not borrow trouble yet.'],
        [0, '08:02', 'camille', 'Good morning Alex! Any word from the appraiser? Julien is pacing the kitchen 😅'],
      ],
    },
    {
      key: 'c_camille', client: 'camille',
      msgs: [
        [-40, '12:10', 'c', 'Hi Alex, it’s Camille. I know Julien likes business in the group chat, but this one is for me: do you know a framer in Miami who understands photographs? 😊'],
        [-40, '12:25', 'me', 'Hi Camille! Yes — Atelier Ocre in Little River does museum mounting for half the galleries in town. Ask for Paloma and tell her I sent you.'],
        [-40, '12:31', 'c', 'Merci!! You’re the best'],
        [-12, '19:02', 'c', 'Can I ask you something without Julien? 🙈 Is it crazy to hang the big seascape in the entry? He thinks it’s too much.'],
        [-12, '19:15', 'me', 'Not crazy at all. The entry wall at Isola Verde is 14 ft — it was made for one big piece. Light it from above and let it be the first thing people see.'],
        [-12, '19:16', 'c', 'I knew it. Showing him this text right now', { react: [{ type: 'laugh', fromMe: true }] }],
        [-1, '15:30', 'c', 'Could you send me the name of the moving company you trust? We need someone careful with the prints and the wine — I want to book for the week of {date:dxClose}.', { ask: 'camille_movers' }],
        [-1, '15:52', 'me', 'Yes! I use two — one for art and wine, one for everything else. Let me make the intros properly tonight.'],
      ],
    },
    {
      key: 'c_victoria', client: 'victoria', pinned: true, unread: 1,
      aiSummary: 'Oceanfront-only cash buyer ($25–45M). Passed on 233 Atlantic Crest (ceilings) and 517 Seagrape Shore (road exposure); interested in the reduced 455 Seagrape Shore and the quiet Golden Beach whisper. Dinner tonight 6:30 at Osteria Vela.',
      msgs: [
        [-41, '19:12', 'c', 'Alex — Sterling Hayes gave me your number. I’m moving my family office to Florida by year-end and need a house on the ocean. I’m in Miami next Thursday and Friday. Can you show me the best three?'],
        [-41, '19:20', 'me', 'Victoria, welcome — Sterling speaks very highly of you. Yes. Before I pick the three: oceanfront only? And how do you feel about Golden Beach versus being south of Bal Harbour?'],
        [-41, '19:31', 'c', 'Oceanfront only. Privacy over scene. I swim every morning, so the beach matters more than the pool.'],
        [-41, '19:33', 'me', 'Understood. Short list tomorrow, with honest notes — including what’s wrong with each one.'],
        [-40, '09:15', 'me', 'First: 233 Atlantic Crest Lane. Beautiful beach, new build, but the ceilings are 10 ft and you will feel it.', { listing: 'mls_gb233' }],
        [-40, '09:17', 'me', 'Second: 517 Seagrape Shore. The best tennis court in Golden Beach, but the motor court sits right on the boulevard.', { listing: 'mls_gb517' }],
        [-40, '09:21', 'c', 'Show me both. And whatever you’d buy if it were your money.'],
        [-24, '18:40', 'me', 'Thank you for today. My read: 233 is too low inside, 517 is too exposed to the road, and you lit up on the beach at 455 but not in the house. I’ll keep digging — the right one may not be on the market.'],
        [-24, '19:02', 'c', 'Correct on all three. Ceilings matter. I have a canvas that needs twenty feet of wall.'],
        [-18, '08:30', 'c', 'Margot will coordinate my next trip. She’ll text you from her own number — please keep prices between us.'],
        [-18, '08:41', 'me', 'Of course. Logistics with Margot, numbers only with you.'],
        [-10, '17:45', 'me', 'Today was useful. For the record: you said the Indian Creek house would be a dream if it ever traded. I’m hearing it might, in the spring. I’ll keep my ear on it.'],
        [-10, '18:05', 'c', 'Do that. Quietly.'],
        [-8, '10:31', 'me', 'Victoria — not oceanfront, so probably not for you, but you asked to see everything serious: 128 Sunset Drive just listed at $18.75M. Bayfront modern, 90-ft dock, roof deck facing the skyline.', { campaign: 'justlisted' }],
        [-8, '10:58', 'c', 'Not oceanfront — pass. Keep sending me the honest ones though.'],
        [-3, '11:12', 'me', 'News: 455 Seagrape Shore just dropped from $32.5M to $29.5M. The sellers have already bought in Palm Beach. Same beach you liked — the house is the question.', { listing: 'mls_gb455' }],
        [-3, '11:30', 'c', 'Ceilings?'],
        [-3, '11:33', 'me', '13 ft on the main level, 11 upstairs, and a two-story gallery wall in the living room. Your canvas would fit.'],
        [-3, '11:41', 'c', 'Interesting. Let’s discuss over dinner.'],
        [-2, '15:40', 'me', 'Booked: {dow:0} at 6:30, Osteria Vela in Bal Harbour. I’ll bring the Golden Beach floor plans and what I know about the quiet one.'],
        [-2, '15:44', 'c', 'Perfect. No more than two houses on paper. I want the story, not a brochure.'],
        [-1, '10:05', 'c', 'Margot will send proof of funds this week — who should it go to? Only you, please.', { ask: 'victoria_pof' }],
        [-1, '10:22', 'me', 'Good question — let me confirm with the Golden Beach owner’s attorney how they want it delivered, and I’ll come back to you before dinner.'],
        [0, '07:52', 'c', 'Confirmed for 6:30. Before tonight — is the Golden Beach owner actually motivated, or just fishing?'],
      ],
    },
    {
      key: 'c_graham', client: 'graham', pinned: true, unread: 2,
      aiSummary: '128 Sunset Drive listed 9 days ago at $18.75M; 14 showings, 3 second showings. First offer last night: $17.2M cash from Reid Castellano’s Greenwich buyer. Graham and Sloane won’t go below $18M and want a read on the buyer.',
      msgs: [
        [-47, '20:10', 'c', 'Thanks for coming by. Sloane liked that you didn’t flatter the house. What’s next?'],
        [-47, '20:22', 'me', 'Next: a pricing memo tomorrow — three comps, the Sunset Isle Way listing, and why I think $18.75M is the number that gets you to $18M+. Then Lena for staging and Kai for photos and drone.'],
        [-46, '09:30', 'me', 'Pricing memo is in your email. Short version: list at $18.75M, expect offers in the high 17s, hold for 18+.'],
        [-46, '10:02', 'c', 'We were thinking 19.5.'],
        [-46, '10:09', 'me', 'I understand. At 19.5 you’re cross-shopped against Sunset Isle Way at 15.9 with a shorter dock. At 18.75 you’re the best house on the island at a price that makes sense. I would rather negotiate down from multiple offers than chase the market.'],
        [-45, '18:30', 'c', 'Ok. 18.75. Sloane agrees. Let’s go.', { react: [{ type: 'like', fromMe: true }] }],
        [-14, '16:00', 'me', 'Lena installs {dow:-12}, Kai shoots {dow:-11} at golden hour, drone {dow:-10} morning. Can Biscuit stay with you during the shoot?'],
        [-14, '16:12', 'c', 'Biscuit will be at daycare all week. He is not a fan of strangers with cameras.'],
        [-11, '19:45', 'me', 'First selects from Kai. The dusk shot of the pool is the cover.', { att: ['listing:own_sunset:3'] }],
        [-11, '19:58', 'c', 'Wow. Sloane is crying a little. Ok, I am too.'],
        [-9, '08:00', 'me', 'We’re live. 128 Sunset Drive is on the MLS at $18.75M, the private blast goes to 18 qualified buyers and agents tomorrow morning, and the broker open is set for {date:brokerOpen}.'],
        [-9, '08:10', 'c', '👍'],
        [-7, '18:30', 'me', 'Showing recap: six showings in 48 hours, two second-showing requests. Feedback: everyone loves the water and the roof deck; one agent called the gym small. Nobody mentioned price.'],
        [-7, '18:42', 'c', 'Who’s serious?'],
        [-7, '18:50', 'me', 'Reid Castellano’s buyer — relocating from Greenwich, paying cash, second showing {dow:-5}. And a local family who has to sell first, so less serious.'],
        [-5, '21:10', 'me', 'Reid’s buyer stayed 90 minutes and brought a contractor. That’s a good sign.'],
        [-1, '20:43', 'me', 'Offer in: $17.2M from Reid’s buyer. Cash, 14-day inspection, 45-day close. Full terms and my recommendation in the morning — my instinct is a counter at $18.3M.'],
        [-1, '20:49', 'c', 'Sloane and I talked. We’re not going below 18.'],
        [-1, '20:51', 'c', 'What’s your read on their buyer? Do they love it or are they fishing?'],
      ],
    },
    {
      key: 'c_sloane', client: 'sloane',
      msgs: [
        [-44, '14:20', 'c', 'Alex, it’s Sloane. Graham will handle the numbers; I’ll handle the house. What do you want gone before photos?'],
        [-44, '14:41', 'me', 'Honestly very little — your taste is the selling point. Family photos, the kids’ trophies and the fridge art. Lena will edit the rest with you.'],
        [-44, '14:45', 'c', 'The trophies stay in the media room or Oliver will disown me 😂', { react: [{ type: 'laugh', fromMe: true }] }],
        [-44, '14:46', 'me', 'Media room it is.'],
        [-12, '10:05', 'c', 'Lena is a genius. She moved two chairs and the living room looks twice as big.'],
        [-12, '10:20', 'me', 'She does that. Wait until you see what she does with the orchids on the terrace.'],
        [-6, '17:10', 'c', 'Can we keep showings to after 10? I have design clients at the house in the mornings this week.'],
        [-6, '17:16', 'me', 'Done — mornings are blocked on the showing calendar through {dow:-1}. Anyone asking earlier gets a 10:15 slot.'],
        [-2, '09:40', 'c', 'Fresh orchids are in. Biscuit is at daycare. The house is ready for its close-up 💐'],
        [-2, '09:42', 'me', 'Perfect. Two showings today, both around 2. I’ll text you when they’re out.'],
        [-2, '15:30', 'me', 'Both out. One said “this is the one I’d buy if I had the money.” The other one has the money and went quiet — which is often better.'],
      ],
    },
    {
      key: 'c_charles', client: 'charles', unread: 1,
      msgs: [
        [-22, '09:30', 'c', 'Mr. Morgan, this is Charles Lowell. Harold Brennan tells me you are the one to call. Margaret and I are considering selling our home in Gables Estates. Could we meet?'],
        [-22, '09:45', 'me', 'Mr. Lowell, thank you for reaching out — and please, it’s Alex. Harold mentioned you might call. I’d love to see the house. Would {dow:-19} at 10 work?'],
        [-22, '10:02', 'c', 'Charles, then. Ten o’clock. Margaret will have coffee.'],
        [-19, '13:00', 'me', 'Thank you both for the tour. The boathouse alone was worth the visit. I’ll put together a pricing view — Gables Estates comps are thin, so I’ll include the 8 Pelican Bight listing and what it tells us.'],
        [-15, '16:20', 'c', 'We have decided to interview two other firms as well. I hope you understand.'],
        [-15, '16:31', 'me', 'Completely — you should. I’d only ask for 45 minutes at the house to show you how I would market it, not just what I would list it for.'],
        [-5, '16:40', 'me', 'Confirmed for {dow:0} at 4:00 at the house. I’ll bring a printed book — I know you prefer paper.'],
        [-5, '16:52', 'c', 'Margaret appreciates that more than you know.'],
        [-1, '18:15', 'me', 'Looking forward to tomorrow. One question so I can be precise: does the 64-ft sportfish convey with the house, or will she be sold separately?'],
        [-1, '18:40', 'c', 'Separately. Though a buyer who wants her is welcome to make me an offer.'],
        [0, '08:47', 'c', 'Good morning. Margaret wants to know whether to have the landscapers come before you arrive at 4, or would you rather see the garden as it is?'],
      ],
    },
    {
      key: 'c_harold', client: 'harold',
      msgs: [
        [-58, '10:15', 'me', 'Harold — a house on Harbor Palm just sold for $7.6M and I thought you’d want to know what yours is worth now.'],
        [-58, '10:40', 'c', 'Seven point six? We paid 4.2! June says don’t tell the kids.', { react: [{ type: 'laugh', fromMe: true }] }],
        [-30, '17:05', 'c', 'June’s knee surgery went well. She’s home and bossing everyone around, which means she’s fine.'],
        [-30, '17:11', 'me', 'Best news all week. Tell her I’m sending soup from the Rusty Anchor whether she wants it or not.'],
        [-14, '09:22', 'c', 'Been thinking. The stairs are going to be a problem for June for a while. And the bank sent a letter about the loan resetting. Can we talk about what selling would look like?'],
        [-14, '09:30', 'me', 'Of course. Let’s talk today — no pressure either way. I’ll show you the numbers both ways: stay and refinance, or sell and go one level.'],
        [-14, '18:00', 'me', 'Thanks for the call. What we covered: the rate resets {date:haroldReset}, likely from 3.125% to around 7%, so the payment goes up roughly $5,800 a month. The house is worth $7.6–8M today. I’ll send one-level options at The Aria and Seaview.'],
        [-14, '18:20', 'c', 'That payment number made June sit down.'],
        [-12, '10:00', 'me', 'This is the one I’d want for you two: The Aria, Residence 1402. One level, the ocean on one side and the Intracoastal on the other.', { listing: 'own_aria1402' }],
        [-12, '10:40', 'c', 'June likes it. $6.95 is a lot for a condo with no yard.'],
        [-6, '09:05', 'me', 'Heads up: Aria 1402 just came down to $6.45M. The estate wants it sold.'],
        [-6, '09:30', 'c', 'Now we’re talking.'],
        [-4, '16:00', 'me', 'Good talking today. Next steps: I’ll pull the Aria 02-line sales history, and we’ll walk 1402 together next week. Thank you for sending Charles my way, by the way.'],
        [-4, '16:12', 'c', 'Charles is a good man, but he will negotiate your fee down to the bone. Don’t let him.'],
        [-1, '11:30', 'c', 'Can you get me the price history on the 02 line at the Aria? June wants to know if 1402 is a deal or just less overpriced.', { ask: 'harold_aria' }],
        [-1, '11:42', 'me', 'Pulling it now — you’ll have every 02-line sale since 2019 by tomorrow.'],
      ],
    },
    {
      key: 'c_priya', client: 'priya', unread: 1,
      msgs: [
        [-19, '14:00', 'c', 'Hi Alex — Maya Goldstein said you’re the person for Miami. We’re moving Ledgerline’s HQ in January and need a house for a family of four (plus a very opinionated cat). Do you have time for a call this week?'],
        [-19, '14:12', 'me', 'Hi Priya — Maya is the best. Congratulations on the move. I’m free tomorrow at 1 or {dow:-17} at 11 (your 8am). What matters most, so I come prepared?'],
        [-19, '14:20', 'c', 'Schools, a real office for Dev with a door that closes, and walkability. We’re used to walking everywhere in SF.'],
        [-8, '17:05', 'me', 'Great to talk. I’ve set up your search for Coconut Grove and the Gables, $4–7.5M, two offices, fenced pool. Let’s meet in person {dow:0} at 9:30 at our office — 3150 Grand Bay Walk in the Grove.'],
        [-8, '17:30', 'c', 'Perfect. Dev will join. We fly in the night before.'],
        [-6, '12:00', 'me', 'This one came on last week: 3270 Kumquat Hammock Lane — fenced pool yard, two offices, and you can bike to Biscayne Prep.', { listing: 'mls_grove3270' }],
        [-6, '12:20', 'c', 'OMG the treehouse vibes. Can we see it while we’re in town?'],
        [-6, '12:22', 'me', 'Already pencilled in for {dow:1} at 9, the morning after our consult.'],
        [-1, '13:10', 'c', 'Could you send the school boundary map for the Grove? Dev wants to sanity-check the commute to his co-working space too.', { ask: 'priya_map' }],
        [-1, '13:25', 'me', 'Yes — a marked-up map tonight, with drive times at 8am.'],
        [-1, '21:12', 'c', 'Landed! See you at 9:30 tomorrow. Should we bring our pre-approval letter or do you have the one Marcus sent?'],
      ],
    },
    {
      key: 'c_ethan', client: 'ethan', channel: 'sms', unread: 1,
      msgs: [
        [-46, '18:30', 'c', 'Hey Alex, Ethan Cole. We talked last year about Pinecrest. We’re ready now — Mara’s practice is doing great and the kids need more space. Still doing this?'],
        [-46, '18:45', 'me', 'Ethan! Absolutely. Congrats to Mara. Same wish list as last year — an acre, a pool, room for Jack’s pitching net?'],
        [-46, '18:52', 'c', 'Same plus a smoker station. Non negotiable 😂'],
        [-31, '19:10', 'me', 'Fun day. Ranking from what I heard: Banyan Ridge first (Mara loved the kitchen), Old Banyan Road second. Banyan Ridge has the better lot — and costs $2.5M more.'],
        [-31, '19:22', 'c', 'Banyan Ridge. But I’m worried about the pool with Wren. She’s 4 and fearless.'],
        [-31, '19:25', 'me', 'Fair. A removable mesh pool fence runs about $6–9K installed and comes down when she’s older. I’ll get a quote.'],
        [-6, '18:20', 'me', 'Offer drafted at $6.75M with a 10-day inspection. It’s been on the market two months — I think there’s room.'],
        [-6, '18:35', 'c', 'Do it.'],
        [-4, '20:00', 'me', 'Counter at $6.9M. I think $6.85M gets it signed tonight.'],
        [-4, '20:05', 'c', '6.85 and we’re done. Mara says yes too.'],
        [-3, '15:50', 'me', 'It’s yours — under contract at $6.85M! Inspection with Hank Morrow {dow:0} at 2:00. Deposit instructions will come from Bayline Title; call Rachel at the number I send separately before you wire anything.'],
        [-3, '16:02', 'c', 'LETS GO. Smoker station here I come'],
        [-1, '17:45', 'c', 'Can you find out if the sellers will leave the pool fence panels in the garage? Mara swears she saw some in there.', { ask: 'ethan_fence' }],
        [-1, '17:58', 'me', 'Good eye. I’ll ask Ricardo first thing.'],
        [0, '07:31', 'c', 'Is the inspector checking the roof with a drone or a ladder? My roofer buddy says to ask.'],
      ],
    },
    {
      key: 'c_mara', client: 'mara',
      msgs: [
        [-31, '21:00', 'c', 'Thank you for today! The kitchen at Banyan Ridge… I’m in love. Don’t tell Ethan before he negotiates 🙊'],
        [-31, '21:08', 'me', 'Your secret is safe. He’s already in love with the smoker spot anyway.'],
        [-20, '12:15', 'c', 'Silly question: which elementary is Banyan Ridge zoned for? Sadie is anxious about switching.'],
        [-20, '12:40', 'me', 'Not silly at all. It’s zoned for Pinecrest Elementary, and it’s eight minutes to Pinecrest Day where Jack already is. I know a parent there who could give Sadie a tour.'],
        [-20, '12:44', 'c', 'That would mean the world'],
        [-3, '16:20', 'c', 'Ethan just called me screaming. THANK YOU 🥹🏡', { react: [{ type: 'love', fromMe: true }] }],
        [-3, '16:24', 'me', 'You two did the hard part. Now let’s get it inspected and closed.'],
        [-2, '09:10', 'c', 'Do you know a pool fence company that’s good with little kids? Wren already asked if the new house has a “big bath”.'],
        [-2, '09:25', 'me', 'I do — SafeHarbor Pool Fences. They did the Duartes’ place. I’ll have them out right after the inspection.'],
      ],
    },
    {
      key: 'c_rafael', client: 'rafael',
      msgs: [
        [-41, '10:00', 'c', 'Alex, Lorenzo me dice que Phase I tiene un PH libre. ¿Es verdad?'],
        [-41, '10:12', 'me', 'Es verdad — PH-B. Four bedrooms, rooftop pool, $9.85M. Lorenzo is holding it 48 hours for his priority list. ¿Te mando los planos?'],
        [-41, '10:13', 'c', 'Sí. Y el price sheet.'],
        [-41, '10:20', 'me', 'Floor plans and the price sheet. Deposits: 10% to reserve, 10% at contract, 10% at groundbreaking, 10% at top-off, 60% at closing.', { att: ['int:3', 'int:5'] }],
        [-31, '19:40', 'c', 'Lucía quiere ver el sales gallery antes de decidir'],
        [-31, '19:44', 'me', 'Perfect — sales gallery {dow:-29} at 5? I’ll ask Lorenzo to have the finish samples out.'],
        [-13, '18:00', 'c', 'Listo. Reservamos PH-B. Gracias hermano 🙏'],
        [-13, '18:05', 'me', '¡Felicidades! You got the best unit in the building. I’ll track every deposit date so you never have to think about it.'],
        [-12, '09:00', 'me', 'Reservation deposit received by escrow ✅ Next: the second 10% is due {date:rafaelDeposit}.'],
        [-5, '14:10', 'c', 'Hablé con Lorenzo. Phase II sale en enero. ¿Me pones en la lista para un 3BR para flip?'],
        [-5, '14:20', 'me', 'Ya estás en la lista — number two, behind a buyer from New York. I’ll push for an early look at the price sheet.'],
        [-5, '14:22', 'c', '👌'],
        [-1, '16:00', 'me', 'Reminder: the second deposit of $985,000 is due {date:rafaelDeposit}. Wire instructions only from the escrow agent — and call to confirm before sending, as always.'],
        [-1, '16:30', 'c', 'Ya sé, ya sé 😂 Lucía is handling it.'],
      ],
    },
    {
      key: 'c_nadia', client: 'nadia',
      msgs: [
        [-27, '22:40', 'c', 'Hello Alex, the concierge at the island club gave me your details. I am looking for a residence on Fisher Island for the winters. My chief of staff Lukas will be in touch about logistics.'],
        [-27, '22:55', 'me', 'Hello Nadia — welcome. I’d be glad to help. Fisher Island has very little inventory, so the best options are often quiet ones. What does a perfect winter week there look like for you?'],
        [-27, '23:10', 'c', 'Tennis every morning, a school for my son Timur nearby, the ocean from the bedroom. And I do not want to renovate.'],
        [-20, '11:00', 'me', 'The Palmyra, Residence 5122 — renovated in 2022, a two-minute walk to the tennis center and the island school, and the ocean from the primary bedroom.', { listing: 'mls_palmyra' }],
        [-20, '11:45', 'c', 'Lovely. What else?'],
        [-20, '11:52', 'me', 'There is also a villa that may come up as an estate sale in about 60 days — five bedrooms, very private. I can’t share the address yet.'],
        [-8, '10:37', 'me', 'Nadia, a new listing on the other side of the bay you may enjoy seeing: 128 Sunset Drive, $18.75M — bayfront modern with a 90-ft dock. Happy to send the floor plan.', { campaign: 'justlisted' }],
        [-6, '15:10', 'me', 'Lovely to speak with you. Confirmed: private tour of Palmyra 5122 {dow:0} at 11:00. You and Lukas are on the gate list; the ferry runs every 15 minutes.'],
        [-6, '15:20', 'c', 'Thank you. Timur will come too, he wants to see the beach.'],
        [-1, '19:30', 'me', 'Looking forward to tomorrow. The forecast is 82° and calm. I’ll meet you at the ferry landing on the island side.'],
        [-1, '19:45', 'c', 'See you tomorrow ☀️'],
      ],
    },
    {
      key: 'c_daniel', client: 'daniel', unread: 1,
      aiSummary: 'Closing on One Harbor Point PH 4501 ($8.95M) {dow:okClose} at Bayline Title; final walkthrough {dow:okWalk} at 4pm. Daniel verified the wire instructions by phone this morning.',
      msgs: [
        [-56, '09:00', 'me', 'Dr. Okafor — Naomi at Northstar Relocation introduced us. Welcome to Miami! When you have a moment, I’d love to hear what you and Andre are looking for.'],
        [-56, '12:30', 'c', 'Thanks Alex. Daniel is fine. Between surgeries — Andre will text you too. Short version: penthouse, light, room for a nine-foot piano, close to the hospital.'],
        [-56, '12:36', 'me', 'A nine-foot grand needs a freight elevator and a floor that can take the weight — I’ll screen for both.'],
        [-50, '19:00', 'c', 'Andre is obsessed with the ceilings at One Harbor Point.'],
        [-50, '19:10', 'me', 'So am I. And the music room already has acoustic panels — someone had your piano in mind.'],
        [-36, '21:00', 'me', 'Jordan and I submitted $8.8M on PH 4501. The seller has been on the market two months; I expect a counter.'],
        [-35, '13:20', 'me', 'Counter at $9.1M. Jordan and I recommend $8.95M with a 30-day close.'],
        [-35, '13:24', 'c', 'Agreed. Andre agrees. Let’s do it.'],
        [-33, '10:10', 'me', 'Under contract at $8.95M 🎉 Inspection is {dow:-31}; Bayline Title will send deposit instructions. Before you wire anything, call Rachel Ostrowski at the number on Bayline’s website — never a number from an email.', { react: [{ type: 'emphasize', fromMe: false }] }],
        [-31, '17:30', 'me', 'Inspection went well. Two items: a sticking terrace slider and a hairline crack in the terrace grout. Both minor; the seller agreed to fix them.'],
        [-31, '17:40', 'c', 'Great.'],
        [-16, '12:00', 'me', 'Appraisal came in at value ✅'],
        [-8, '10:33', 'me', 'Daniel, not for you — but if colleagues at Bayview ask: 128 Sunset Drive just listed at $18.75M, bayfront with a 90-ft dock.', { campaign: 'justlisted' }],
        [-5, '09:45', 'me', 'Clear-to-close is the last item — Marcus expects the underwriter to sign off by {dow:okWalk}. Final walkthrough {dow:okWalk} at 4pm, closing {dow:okClose} at 10am at Bayline.'],
        [-5, '10:20', 'c', 'Perfect. I’m in surgery until 2 that day but can do 4.'],
        [-3, '13:05', 'me', 'As promised: Bayline will email the final wire instructions {dow:0}. Call Rachel at the number I gave you and verify every digit before sending. If anyone emails “updated” instructions, it is fraud — call me.'],
        [-3, '13:15', 'c', 'Understood. Andre printed your text and taped it to the fridge.'],
        [-1, '16:20', 'me', 'Movers are booked for {dow:okClose} afternoon, right after closing. The building needs the movers’ insurance certificate by {dow:okWalk} — I sent the template to Andre.'],
        [-1, '16:31', 'c', 'Andre is on it.'],
        [0, '08:10', 'c', 'Got the wire instructions email from Bayline — called Rachel and verified like you said. Anything else I need to do before {dow:okClose}?'],
      ],
    },
  ];
};
